chore(db/migration): check migration regex path before db changes
Kong/kong pull request #10089
Opened 2023-01-10 11:58 UTC by chronolaw

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

In `kong migrations up`, it will print an error log to notify the user if there is an incompatible regex path route:

```
2022/12/30 09:27:37 [error] Regex path may not work with router flavor 'traditional_compatible', route id: 0950d523-aa5e-4d05-a1af-928ea5c3aa99, err:  --> 1:2
  |
1 | (http.path ~ "^/\\/*/user$")
  |  ^------------------------^
  |
  = regex parse error:
    ^/\/*/user$
      ^^
error: unrecognized escape sequence
```

It will replace #9992.

See KAG-329.

2023-01-10 12:27 UTC, chronolaw commented on kong/db/schema/others/migrations.lua
> +          { up_t = { type = "function" } },
Here `up_t` means `up try` or `up test`.

2023-01-10 18:03 UTC, colinh-kong requested changes
Is there an early preview of documentation related to how a user achieves a zero-downtime upgrade should they have an incompatible route?

2023-01-11 00:58 UTC, chronolaw commented
This change will only be applied to 3.1.x, so I created another PR #10092.

2023-01-11 00:58 UTC, closed without merging

2023-01-11 01:02 UTC, chronolaw commented
> Is there an early preview of documentation related to how a user achieves a zero-downtime upgrade should they have an incompatible route?

Sorry, till now there is no document for it. But I think when the PR #10092 is ready we will have one.