feat(balancer): add KONG_UPSTREAM_DNS_TIME ctx
Kong/kong pull request #10355
Opened 2023-02-23 07:22 UTC by attenuation

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #_[issue number]_

2023-02-23 09:19 UTC, sabertobihwy commented on kong/runloop/balancer/targets.lua
> +end
Just a small suggestion, this function appears twice, could it be placed in a module like tools or utils.

2023-02-24 08:05 UTC, chronolaw commented on kong/tools/utils.lua
> +local update_time   = ngx.update_time
These two lines are only used by `get_updated_now_ms`, 
we should move these two lines into a `do end` block,
like `sha256_hex` did.

2023-02-24 19:49 UTC, hbagdi commented
@locao understands balancer and must sign off to make sure that the latency is being measured correctly.
We also need a test that puts Kong in a stat where it performs a synchronous DNS resolution while proxying a request and we observe the appropriate latency in here.

We want to capture this metric in the log-serializer and then add a test to make sure that this is emitted in `http-log` and other metric plugins.

2023-02-24 22:24 UTC, locao commented
I labeled this PR as "discussion" so we can quickly talk about it offline before merging.

2023-02-28 23:41 UTC, hbagdi commented
When and where is this discussion going to happen?

2023-03-01 13:38 UTC, locao commented
> When and where is this discussion going to happen?

It happened in FTI-4826. I think we are good to continue.

2023-03-07 17:44 UTC, locao commented
I converted this to draft PR, as the comments in FTI-4826 are still to be addressed.

2023-03-28 17:12 UTC, locao requested changes
Can you add some testing, please?

2023-03-28 17:12 UTC, locao commented on kong/init.lua
> +    end
```suggestion
    else
      ctx.KONG_UPSTREAM_DNS_TIME = 0
    end
```
Let's keep the metric always present, even when we get a cache hit.

2023-04-10 16:18 UTC, hbagdi commented
ping @locao for another round

2023-04-11 08:51 UTC, hanshuebner submitted a review, later dismissed
@attenuation Please update the pull request description to include an actual description and make sure that all checklist items are addressed.

2023-04-18 13:12 UTC, locao requested changes
@attenuation please, add some tests to validate the new feature, a changelog entry and fix the merge conflict.

2023-04-18 13:59 UTC, hanshuebner reviewed
Why is a new function introduced that works with non-standard millisecond resolution?  Is it a requirement that `KONG_UPSTREAM_DNS_TIME` is presented in milliseconds?

All the extra localization makes the change much bigger than it needs to be, with questionable benefit.

2023-04-25 08:15 UTC, attenuation commented
> Why is a new function introduced that works with non-standard millisecond resolution? Is it a requirement that `KONG_UPSTREAM_DNS_TIME` is presented in milliseconds?
> 
> All the extra localization makes the change much bigger than it needs to be, with questionable benefit.

We need to get accurate time, and the time returned by `ngx.now()` is cached by Nginx, which is refreshed each time an epoll event loop is waited. As we need to get the time during the connection, we have to call `ngx.update_time` to refresh the cached time.
Also, I encapsulated this logic in a function since it's being used in many places, and there is no problem with that.

2023-04-26 13:58 UTC, locao commented
> Why is a new function introduced that works with non-standard millisecond resolution? Is it a requirement that `KONG_UPSTREAM_DNS_TIME` is presented in milliseconds?

That's not a new function, it was moved to `utils` to be used by the load-balancer code. Besides that, all other latencies are measured in ms (using the same function), so I think it's right to keep the same resolution.

2023-04-26 14:01 UTC, locao approved these changes
This change seems good to go. Good job!

I'll just wait for the tests to go green before merging.

2023-04-26 16:30 UTC, merged