feat: added optional support to protoc
Kong/kong pull request #10388
Opened 2023-02-28 13:09 UTC by AliRostami1

added support to protobuf compiler to parse optional fields

### Summary

grpc-web does not support optional fields in proto3 format

### Checklist

- [x] The Pull Request has tests
- [x] There's an entry in the CHANGELOG
- [x] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* grpc-web now supports optional fields in proto3 format. 

### Issue reference

2023-02-28 13:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=10388) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=10388) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=10388) it.</sub>

2023-02-28 18:13 UTC, gszr requested changes
@AliRostami1, thank you for contributing to Kong! Please add a test case for this; note that we use a `spec/fixtures/grpc/hello.proto` fixture for grpc-web tests, where you may add optional fields if needed for testing. (Also, please sign the CLA)

2023-03-06 16:21 UTC, gszr requested changes

2023-03-06 16:21 UTC, gszr commented on spec/fixtures/grpc/hello.proto
> +  string reply = 1;
Let's not modify existing fields. Also, please make sure to add a new, separate, _test case_ that will leverage this new feature.

2023-03-07 04:22 UTC, fffonion commented
we might also want equivelant feature in grpc-gateway plugin, @AliRostami1 could you also include it in this PR?

2023-03-07 11:41 UTC, gszr commented
@fffonion maybe this could be moved into `kong.tools.grpc` (`:new`)?

2023-03-08 06:45 UTC, fffonion commented
i agree moving to `kong.tools.grpc` is a good idea!

2023-03-21 21:28 UTC, closed without merging