fix(schema): bundled plugin schema must have protocols field
Kong/kong pull request #10431
Opened 2023-03-06 07:41 UTC by vm-001

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #_[issue number]_

2023-03-06 10:34 UTC, hanshuebner requested changes

2023-03-06 10:34 UTC, hanshuebner commented on kong/db/schema/metaschema.lua
> +local bundled_plugins = constants.BUNDLED_PLUGINS
Suggest keeping the capitalization (`BUNDLED_PLUGINS`) when locallizing to make it easier to understand that a global variable is accessed.

2023-03-06 22:13 UTC, gszr submitted a review, later dismissed
Can this check be moved into the plugins custom DAO instead? Or perhaps the plugins schema itself? The metaschema module should not need to carry knowledge of any specific entity structure or schema.

2023-03-07 02:48 UTC, vm-001 commented
@gszr This PR aims to ensure the existing and feature bundled plugin must define the `protocols` field in the schema.  I think moving the check to custom DAO or plugin schema itself doesn't meet the aim.

"metaschema module should not need to carry knowledge of any specific entity structure or schema."  This make sense to me. 

Another approach is moving the check into the function `Plugins:load_plugin_schemas(plugin_set)` https://github.com/Kong/kong/blob/master/kong/db/dao/plugins.lua#L303 

What do you think?

2023-03-07 11:32 UTC, gszr commented
> Another approach is moving the check into the function `Plugins:load_plugin_schemas(plugin_set)` https://github.com/Kong/kong/blob/master/kong/db/dao/plugins.lua#L303
> 
> What do you think?

This module is what I meant by plugins custom DAO; this would indeed be more appropriate location for such check 👍🏻

2023-03-15 14:42 UTC, merged