chore(plugin): convert traceid in http response headers to hex format
Kong/kong pull request #10534
Opened 2023-03-21 12:15 UTC by sabertobihwy

### Summary

### Checklist

- [x] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [x] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference
#10270

Fix #_[issue number]_

2023-03-22 20:26 UTC, gszr requested changes

2023-03-22 20:26 UTC, gszr commented on kong/plugins/opentelemetry/handler.lua
> +    local trace_id = to_hex(trace_id)
```suggestion
    trace_id = to_hex(trace_id)
```

2023-03-24 18:11 UTC, gszr approved these changes

2023-03-24 18:12 UTC, merged

2023-03-27 20:11 UTC, hbagdi commented
This seems to be a fix rather than a chore. Please follow our contributor guidelines (CONTRIBUTING.md).

2023-04-03 16:17 UTC, hbagdi commented
@gszr Ping on above.

2023-04-04 17:26 UTC, hbagdi commented
@gszr Poke

2023-04-05 14:31 UTC, gszr commented
@hbagdi I have taken a few minutes to check on this; a pending CE to EE merge is in order before this can be cherry-picked.

2023-04-05 14:44 UTC, gszr commented
> This seems to be a fix rather than a chore. Please follow our contributor guidelines (CONTRIBUTING.md).

This had been fixed at merge time -- see the merged commit 14a64bf