test(plugin): otel reconfigure not work #KAG-1061
Kong/kong pull request #10666
Opened 2023-04-13 07:31 UTC by StarlightIbuki

### Summary

Improvement of batch queue fixed the OTEL reconfigure issue. We need to add test.

### Checklist

- [x] The Pull Request has tests
- [x] There's an entry in the CHANGELOG
- [ ] <s>There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE</s> N/A

### Full changelog

* Cherry-pick coroutine-based HTTP mock helper function
* Regression test for the issue

### Issue reference

Test of KAG-1061

2023-04-13 12:38 UTC, hanshuebner requested changes
Please update the title of the PR to describe the issue.  Also update the summary in the description to include the problem, the root cause and the solution.  It currently seems to say that this PR fixes an issue where in reality the issue was fixed by the queueing changes and what it contains is just the regression test.

2023-04-14 06:13 UTC, StarlightIbuki commented on spec/helpers.lua
This is not a duplication. `http_server` uses a thread and `http_mock` uses a coroutine. The coroutine implementation is more deterministic and thus less flaky, but we choose to not retire `http_server` for now as it involves a lot of changes in the test suit (plus I need to convince people to switch to this).

2023-04-14 06:48 UTC, hanshuebner commented on spec/helpers.lua
Please add a comment to the threads based implementation, pointing out that `http_mock` should be used instead, and open a KAG ticket "Replace usage of `helpers.http_server` by `helpers.http_mock`".

2023-04-14 09:40 UTC, StarlightIbuki commented on spec/helpers.lua
Please refer to https://konghq.atlassian.net/browse/KAG-1148

2023-04-14 09:55 UTC, hanshuebner commented on spec/helpers.lua
I would still like to see a deprecation comment in helpers.lua to make people aware of the issue.

2023-04-19 02:44 UTC, StarlightIbuki commented on spec/helpers.lua
@hanshuebner I've added comments to `http_server`.

2023-04-19 04:54 UTC, hanshuebner approved these changes

2023-04-19 04:54 UTC, merged