Fix queue coalescing bugs
Kong/kong pull request #10679
Opened 2023-04-14 15:07 UTC by hanshuebner

### Summary

This PR fixes two bugs in the queue coalescing logic:

 - The `max_coalesce_time` parameter was specified to be seconds, but was interpreted as milliseconds.  The incorrect scaling is now fixed.
 -  When `max_coalesce_time` set to a larger value, the queue handler would not exit waiting for new entries when a graceful shutdown was inititated.  This could lead to data loss.  The code has been changed so that it is periodically checked whether the worker is shutting down while waiting for new entries.

Thanks to @27ascii for [reporting](https://github.com/Kong/kong/pull/10172#discussion_r1166358623) these bugs!

### Checklist

- [X] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG N/A (unreleased version)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com N/A

### Issue reference

Fix KAG-1218 and KAG-1219

2023-04-17 06:42 UTC, 27ascii reviewed
LGTM
I've verified the shutdown behaviour, everything is now working as expected - all pending entries in the queue are send on `kong reload` or `kong quit`.
Thanks for addressing this so quickly.

2023-04-17 07:15 UTC, 27ascii commented
I just saw that `initial_retry_delay` has no initial value defined and fails here https://github.com/Kong/kong/blob/0f1017bca36776ec0a0c0d2fb6ff1126747e71ec/kong/tools/queue.lua#L257
What would be a good initial value?

2023-04-17 07:22 UTC, 27ascii commented
Sorry, please ignore the comment about `initial_retry_delay`. I saw it is defined in schema. Maybe it should be mentioned here:
https://github.com/Kong/kong/blob/0f1017bca36776ec0a0c0d2fb6ff1126747e71ec/kong/tools/queue.lua#L25-L34

2023-04-18 11:40 UTC, jschmid1 commented on spec/03-plugins/01-legacy_queue_parameter_warning_spec.lua
> +      local body = assert.res_status(200, res)
should be possible with

```lua
db:truncate("plugins")
```

2023-04-18 11:45 UTC, jschmid1 commented on spec/01-unit/27-queue_spec.lua
>      assert.same(configuration_sent, configuration_received)
Lets move the assertion into the loop to prevent time senstive false-positives

2023-04-18 11:52 UTC, jschmid1 requested changes

2023-04-18 11:52 UTC, jschmid1 commented on spec/02-integration/15-queues/01-shutdown_spec.lua
> +            max_batch_size = 1000,
We may consider using MAX and MIN limits where we know we get into trouble.

2023-04-18 13:10 UTC, jschmid1 approved these changes
👍🏻

2023-04-18 13:11 UTC, merged