chore(ci): improve visibility of failed backport bot merges
Kong/kong pull request #10674
Opened 2023-04-14 06:46 UTC by pluveto

### Summary

#### Background 

The failure comment like this [one](https://github.com/Kong/kong-ee/pull/4408#issuecomment-1404006790) is easy to miss.

These failures should be very noisy to prevent cases where a fix is not carried across the required release branches.

#### This PR

Sends a Slack message to Gateway channel when a 'team-gateway-bot' makes a comment containing 'To backport manually, run these commands in your terminal' on an PR comment issue.

### Checklist

- [ ] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix KAG-849

2023-04-14 06:46 UTC, pluveto commented
`SLACK_WEBHOOK_URL` Need to be configured

2023-04-14 08:17 UTC, pluveto commented
Now support mention users. @dndx need set `vars.SLACK_MAPPING`

2023-04-21 15:53 UTC, RobSerafini commented
@kikito @tyler-ball - please recommend a reviewer for the PR.

2023-04-25 04:22 UTC, ADD-SP requested changes

2023-04-25 04:22 UTC, ADD-SP commented on .github/workflows/backport-fail-bot.yml
> +            console.log(`::set-output name=payload::${JSON.stringify(payload)}`);
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The `::set-output` has been deprecated, could you please use the newer way?

2023-04-25 06:25 UTC, ADD-SP approved these changes

2023-04-25 20:30 UTC, hbagdi commented
Why not create a Jira and assign the PR author?
Slack is yet another place where these failures will be ignored, no?

2023-04-26 02:39 UTC, pluveto commented
> Why not create a Jira and assign the PR author? Slack is yet another place where these failures will be ignored, no?

I think we should do experiments before drawing conclusions

2023-05-03 10:51 UTC, kikito commented
I have assigned @samugi on this one as a reviewer

2023-05-03 13:02 UTC, samugi commented
A comment in the thread above says: `@dndx need set vars.SLACK_MAPPING`, is this action still pending / is that the reason for the "do-not-merge" label @dndx @pluveto?

2023-05-03 13:07 UTC, pluveto commented
> A comment in the thread above says: `@dndx need set vars.SLACK_MAPPING`, is this action still pending / is that the reason for the "do-not-merge" label @dndx @pluveto?

Yes

2023-05-08 02:13 UTC, chronolaw commented
This PR should not be included in milestone 3.3.

2023-05-11 09:27 UTC, dndx commented
This PR is out of date and some variable names has since changed. I need to work on fixing it before merging.

2023-05-18 09:52 UTC, ADD-SP commented
Close and move to https://github.com/Kong/kong/pull/10894

2023-05-18 09:52 UTC, closed without merging