Update kong.conf.default
Kong/kong pull request #10789
Opened 2023-05-04 22:52 UTC by DeclanPaulKeane

### Summary

This is my first time doing this, so apologies if I make a mistake. The path for status_listen is missing and the docs need to be updated.

### Checklist

- [ x] The Pull Request has tests
- [ x] There's an entry in the CHANGELOG
- [ x] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

### Issue reference

2023-05-04 22:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=10789) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=10789) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=10789) it.</sub>

2023-05-04 23:01 UTC, lena-larionova approved these changes
LGTM, will pull it into the docs once this is merged.

2023-05-08 21:32 UTC, hbagdi requested changes
This change doesn't look right.
There are more endpoints available than /status on the status endpoint.
@Guaris is working on a spec that lays them out.

2023-05-24 00:07 UTC, hbagdi commented
Here is the spec: https://developer.konghq.com/spec/9542436a-58d1-4522-a00b-32125b5940f0/5feb007a-348b-486d-8d06-92f615471d22

Please re-open if needed.

2023-05-24 00:07 UTC, closed without merging