perf(*): use cycle aware deep copy instead
Kong/kong pull request #10970
Opened 2023-05-30 20:33 UTC by bungle

### Summary

Penlight `tablex.deepcopy` is cycle-aware, and it is almost never requirement to clone metatables that `kong.tools.utils.deep_copy` does by default (and it is not cycle-aware).

Changing to cycle-aware deepcopy, the memory usage of workers especially on dataplanes and dbless nodes where declarative config requires a lot of deepcopying of records.

In my testing with:
```
KONG_DATABASE=off \
KONG_ROLE=data_plane \
KONG_CLUSTER_CONTROL_PLANE=cp.test:8005 \
KONG_CLUSTER_CERT=cluster.crt \
KONG_CLUSTER_CERT_KEY=cluster.key \
kong start -p dp
```

Before this commit:
79 MB

After this commit:
70 MB

So about 9 MB reduction in memory usage per worker.

2023-05-30 20:48 UTC, bungle commented
There might be more to it. I was able to reduce 7 MB more easily. But I will do that in another PR. This at least should be safe.

2023-06-09 13:39 UTC, jschmid1 requested changes
What about still using `utils.deep_copy` but changing the implementation of `utils.deep_copy` to just 

``` lua
local tablex_deepcopy = require("pl.tablex").deepcopy
-- ...
function _M.deep_copy(data)
    return tablex_deepcopy(data)
end
```

This should help with adoption in EE also.

2023-06-09 17:27 UTC, bungle commented
> What about still using `utils.deep_copy` but changing the implementation of `utils.deep_copy` to just
> 
> ```lua
> local tablex_deepcopy = require("pl.tablex").deepcopy
> -- ...
> function _M.deep_copy(data)
>     return tablex_deepcopy(data)
> end
> ```
> 
> This should help with adoption in EE also.

@jschmid1,

I tried it, but it seems some code require the non-cycle aware copy that utils.deep_copy does. So decided to keep backward compatibility on that.

2023-06-13 09:54 UTC, jschmid1 commented
I still think we should introduce an abstraction that allows us to test and document the behavior

if we still need deep_copy to maintain backwards compat then what about introducing a new function for deep_copy that is cycle aware.

Something like `deep_copy_cycle_aware` ?

2023-06-14 11:22 UTC, bungle commented
> I still think we should introduce an abstraction that allows us to test and document the behavior
> 
> if we still need deep_copy to maintain backwards compat then what about introducing a new function for deep_copy that is cycle aware.
> 
> Something like `deep_copy_cycle_aware` ?

Abstraction introduced.

2023-06-20 09:00 UTC, bungle commented
EE cherry: https://github.com/Kong/kong/pull/10970

2023-06-20 10:20 UTC, jschmid1 approved these changes
looks good 🚀

2023-06-20 10:21 UTC, merged