fix(pdk): change lmdb env info metrics
Kong/kong pull request #11032
Opened 2023-06-08 07:12 UTC by oowl

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #_[issue number]_

2023-06-21 17:57 UTC, hbagdi commented
If this doesn't go in, @oowl please make sure to revert the PR that added LMDB metrics. We must not release a feature that is not ready or will have breaking changes.

2023-06-22 02:58 UTC, oowl commented
@hbagdi  I promise that this PR will be released in version 3.4, and I will continue to push it forward when I come back from PTO in this week.

2023-06-27 08:14 UTC, oowl commented
hold waiting for sister PR https://github.com/Kong/lua-resty-lmdb/pull/38 merged, I will change `.requirement` to `lua-resty-lmdb` bump version.

2023-06-28 02:32 UTC, chronolaw approved these changes
Ready to merge when lmdb version bump.

2023-06-29 06:28 UTC, dndx commented
There are some typo in the variable name, and it needs to be fixed before merging.

2023-07-05 01:35 UTC, chronolaw commented on CHANGELOG.md
> +  [#11032](https://github.com/Kong/kong/pull/11032)
These entry should move to `3.4.0 changed` section, not `3.3.0`.

2023-07-05 09:43 UTC, chronolaw commented on CHANGELOG.md
> +  [#11032](https://github.com/Kong/kong/pull/11032)
Should remove this entry (in 3.3.0 section).

2023-07-05 09:43 UTC, chronolaw commented on CHANGELOG.md
> +  [#11032](https://github.com/Kong/kong/pull/11032)
Should these move to `Changed` section? It seems not to be fixes.

2023-07-05 09:43 UTC, chronolaw commented
Add lmdb version bump entry please.

2023-07-05 10:27 UTC, chronolaw approved these changes

2023-07-05 11:15 UTC, dndx requested changes

2023-07-05 11:15 UTC, dndx commented on CHANGELOG.md
> +- Rework pdk lmdb environment information with `kong.node.get_memory_stats`.
This feature seems to be unreleased, and we should change the existing changelog instead.

2023-07-07 05:47 UTC, dndx commented on kong/plugins/statsd/log.lua
>          local lmdb_used_space_metric_name = conf.hostname_in_prefix and "lmdb.used_space" or string_format("node.%s.lmdb.used_space", hostname)
We should fix this metrics name to be consistent with the API as well.

`dbless.lmdb.in_use_bytes`
`dbless.lmdb.map_size_bytes`

Also we can expose `dbless.lmdb.max_readers` and `dbless.lmdb.num_readers` as well. More metrics is always better.

2023-07-10 07:52 UTC, chronolaw commented
According to the discussion in https://github.com/Kong/lua-resty-lmdb/pull/38, should we close this PR?

2023-07-11 07:36 UTC, oowl commented
Close it for https://github.com/Kong/lua-resty-lmdb/pull/38

2023-07-11 07:36 UTC, closed without merging