feat(cache): add cache:renew function and mlcache refactorings
Kong/kong pull request #11038
Opened 2023-06-08 21:55 UTC by bungle

### Summary

1. removes fallbacks needed for older OpenResty support
2. uses SHM native TTLs only instead, and stores just the value in SHM instead of storing `<type>:<created_at>:<ttl>:<value>`.
3. implements `:renew` in mlcache
4. implements `:renew` in kong cache
5. changes kong.vault to use `:renew` function instead of calling `:peek` etc. for better concurrency control

KAG-1698

2023-07-05 06:29 UTC, hanshuebner requested changes
Looks good - Following up to our discussion yesterday, I think it would be better to replace the use of `rotate` by `renew`.

2023-07-05 06:55 UTC, chronolaw commented
Could we still keep `kong.cache.marshall` as an interlayer? Though it is just a alias of `string.buffer.encode`.

2023-07-05 08:10 UTC, hanshuebner commented
> Could we still keep `kong.cache.marshall` as an interlayer? Though it is just a alias of `string.buffer.encode`.

Why do you want to keep it?

2023-07-05 10:44 UTC, bungle commented
> Looks good - Following up to our discussion yesterday, I think it would be better to replace the use of `rotate` by `renew`.

@hanshuebner, I will make a change and ping you back.

2023-07-05 12:09 UTC, hanshuebner approved these changes

2023-07-05 12:11 UTC, merged

2024-03-12 06:19 UTC, chobits commented on kong/resty/mlcache/init.lua
> +            return nil, "could not read from lua_shared_dict: " .. shmerr
hi @bungle do we need to unlock `lock` object here before it returns nil?

2024-03-12 06:26 UTC, chobits commented on kong/resty/mlcache/init.lua
> +            return nil, "could not read from lua_shared_dict: " .. shmerr
Seems no bug here, from the lua-resty-lock doc:


> If the [unlock()](https://github.com/openresty/lua-resty-lock#unlock) method is never called after this method call, the lock will get released when
> 
> the current resty.lock object instance is collected automatically by the Lua GC.
the exptime for the lock entry is reached.



but I think we could `call unlock_and_ret()` to align with the `get()` api's action.