perf(plugin/prometheus): use ngx.re.match to replace string.match
Kong/kong pull request #11126
Opened 2023-06-27 03:32 UTC by chronolaw

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #_[issue number]_

2023-06-27 08:24 UTC, jschmid1 commented
Do we have exsting tests for this piece of code? If not, this would be a good time to add some. What do you think @chronolaw ?

2023-06-27 11:14 UTC, chronolaw commented
It seems that it is the responsibility of unit tests, but `spec/03-plugins/26-prometheus` can not cover this situation.

2023-06-27 13:58 UTC, jschmid1 commented
How about factoring out the piece that is supposed to match to a separate function that can be tested via unit tests?

2023-06-28 03:31 UTC, chronolaw commented
These functions are used internally, they are not exposed for testing.
And Prometheus module need to be inited in `init` and `init_worker` phase,
this makes it hard to do unit test for internal small functions.

A way may be exposing these functions only for testing, such as `Prometheus._check_metric_and_label_names`,
but is it worthy?

2023-06-28 05:25 UTC, hanshuebner requested changes
Please update the pull request description.

2023-06-28 06:13 UTC, sabertobihwy approved these changes

2023-06-28 08:08 UTC, chronolaw commented
PR #11137 will add the tests for this PR and #11115.

2023-06-28 11:02 UTC, hanshuebner requested changes
Using the `i` flag for case insensitive matching should be faster.

2023-06-28 11:02 UTC, hanshuebner commented on kong/plugins/prometheus/prometheus.lua
> +local LABEL_NAME_REGEX  = [[^[a-zA-Z_][a-zA-Z0-9_]*$]]
```suggestion
local METRIC_NAME_REGEX = [[^[a-z_:][a-z0-9_:]*$]]
local LABEL_NAME_REGEX  = [[^[a-z_][a-z0-9_]*$]]
```

2023-06-28 11:02 UTC, hanshuebner commented on kong/plugins/prometheus/prometheus.lua
> +  if not ngx_re_match(metric_name, METRIC_NAME_REGEX, "jo") then
```suggestion
  if not ngx_re_match(metric_name, METRIC_NAME_REGEX, "ijo") then
```

2023-06-28 11:02 UTC, hanshuebner commented on kong/plugins/prometheus/prometheus.lua
> +    if not ngx_re_match(label_name, LABEL_NAME_REGEX, "jo") then
```suggestion
    if not ngx_re_match(label_name, LABEL_NAME_REGEX, "ijo") then
```

2023-06-28 11:06 UTC, chronolaw commented
Good suggestions. I will change these regex in CE PR.

2023-06-28 11:19 UTC, hanshuebner approved these changes

2023-06-29 06:11 UTC, windmgc approved these changes
Merging this since tests will be added in separate PR

2023-06-29 06:11 UTC, merged