doc(CONTRIBUTING): mention changelog
Kong/kong pull request #11535
Opened 2023-09-10 06:58 UTC by fffonion

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been added to `CHANGELOG/unreleased/kong` or adding `skip-changelog` label on PR if unnecessary. [README.md](https://github.com/Kong/kong/blob/master/CHANGELOG/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #_[issue number]_

2023-09-10 07:31 UTC, chronolaw commented on CONTRIBUTING.md
> +documentation-only changes, require a changelog entry to present.
```suggestion
documentation-only changes, requires a changelog entry to present.
```

2023-09-10 08:19 UTC, chronolaw commented on CONTRIBUTING.md
> +    - [Writing performant code]
```suggestion
    - [Writing performant code](#writing-performant-code)
```
Do we miss this link?

2023-09-11 02:49 UTC, vm-001 commented
lgtm

2023-09-26 15:02 UTC, hanshuebner requested changes
Please adapt to the recent changelog changes.

2023-10-04 14:40 UTC, hanshuebner approved these changes

2023-10-04 14:40 UTC, merged

2023-10-08 03:09 UTC, AndyZhang0707 commented
@fffonion please cherry-pick to ee. thx.