[backport] fix(vault): vault references may be dropped from rotation
Kong/kong pull request #11567
Opened 2023-09-13 15:30 UTC by bungle

### Summary

Backports the fix from EE:
https://github.com/Kong/kong-ee/pull/6444/commits/50eaa56a6f4f7c9e4a8c8336579f005b462a1b46

Fixes issue where Vault references may be dropped from rotation in case a too small value was configured in `config.resurrect_ttl` OR `config.neg_ttl`.

This is fixed by setting a constant value of:
```
local SECRETS_CACHE_MIN_TTL = ROTATION_INTERVAL * 2
```

(the rotation interval is by default 60 seconds).

2023-09-14 12:08 UTC, hanshuebner approved these changes

2023-09-14 12:09 UTC, hanshuebner requested changes
Please add a test and include the checklist from the PR template.

2023-09-18 07:05 UTC, bungle commented
> Please add a test and include the checklist from the PR template.

@hanshuebner there is already tests in EE. This is a backport from EE -> CE.

2023-09-18 07:50 UTC, hanshuebner approved these changes

2023-09-18 07:50 UTC, merged

2023-09-25 17:22 UTC, kikito commented
@bungle shouldn't this be backported to 3.4