FIX:Repeated sslhandshake in [tcp-log] plugin
Kong/kong pull request #11803
Opened 2023-10-22 06:58 UTC by chenyyyang

### Summary

FIX: [Repeated sslhandshake in [tcp-log] plugin](https://github.com/Kong/kong/issues/11052)

### Checklist

- [ √] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

change the code in  tcp-log/handler.lua

### Issue reference

Fix #[_[11052]_](https://github.com/Kong/kong/issues/11052)

2023-10-22 06:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=11803) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=11803) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=11803) it.</sub>

2023-10-22 06:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=11803) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=11803) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=11803) it.</sub>

2023-10-23 06:34 UTC, tzssangglass commented
hi @chenyyyang , we need a changelog(you can learn from other PRs), and if you can add test cases to cover this fix, it maybe better!

2023-10-23 06:43 UTC, chenyyyang commented
I have already browsed the other PRs but no changelog could be found.Could you provide a template?

2023-10-23 06:46 UTC, tzssangglass commented
> I have already browsed the other PRs but no changelog could be found.Could you provide a template?

https://github.com/Kong/kong/pull/11786/files#diff-1c9ba4aa7ac45698a290b3506fc00dc16289cd098483e8e7e2bb580d0b40a8c2

2023-10-23 12:17 UTC, bungle commented
@chenyyyang, looks good! Just add the changelog. See: https://github.com/Kong/kong/blob/master/changelog/changelog-template.yaml

Add change-log here:
https://github.com/Kong/kong/tree/master/changelog/unreleased/kong

Give it a name: `fix-tcp-log-sslhandshake.yml`

2023-10-23 12:26 UTC, chenyyyang commented
Sure.I have added the changelog.

2023-10-24 12:37 UTC, bungle approved these changes

2023-10-24 14:54 UTC, tzssangglass commented on changelog/unreleased/kong/fix-tcp-log-sslhandshake.yml
> +message: fix an issue that repeated ssl handshake in tcp-log plugin
```suggestion
message: **tcp-log**: fix an issue that repeated ssl handshake
```

2023-10-24 15:01 UTC, chenyyyang commented
Done @tzssangglass

2023-10-24 16:11 UTC, tzssangglass approved these changes

2023-10-24 16:14 UTC, tzssangglass requested changes

2023-10-24 16:14 UTC, tzssangglass commented on changelog/unreleased/kong/fix-tcp-log-sslhandshake.yml
> +message: **tcp-log**: fix an issue that repeated ssl handshake
```suggestion
message: "**tcp-log**: fix an issue that repeated ssl handshake"
```

previously, I mislead you. It should have double quotation marks added 😅

2023-10-24 21:41 UTC, chenyyyang reviewed
done？

2023-10-25 03:44 UTC, tzssangglass approved these changes

2023-10-26 06:25 UTC, merged