fix(request-debugging): fix can't set root properties when enable the…
Kong/kong pull request #11808
Opened 2023-10-23 06:45 UTC by ADD-SP

… phase filter

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #_[issue number]_

2023-10-24 17:55 UTC, brentos approved these changes

2023-10-26 13:07 UTC, hanshuebner requested changes
Please describe the problem, the cause and the solution in the pull request description.  Currently, the description contains information that is not helpful when trying to understand what the change is about - It seems that there is a field rename and that root context properties now can always be set even if `should_run()` returns false.  Why?

2023-10-26 13:16 UTC, ADD-SP commented
> > Please describe the problem, the cause and the solution _**in the pull request description**_.

@hanshuebner done

2023-10-26 13:17 UTC, hanshuebner approved these changes

2023-10-26 13:18 UTC, merged

2023-10-31 08:27 UTC, AndyZhang0707 commented
@ADD-SP pls cherry-pick to ee.