chore: disable `dedicated_config_processing by default
Kong/kong pull request #11842
Opened 2023-10-25 11:10 UTC by jschmid1

**DO NOT MERGE | This patch exists only to simplify the switch-back to the old default**

2023-10-26 15:19 UTC, kikito commented
We have decided to go this route (turn it OFF by default). Rewording the PR request body, making it un-draft and rebasing as a result.

2023-10-26 15:21 UTC, kikito approved these changes

2023-10-26 15:26 UTC, hanshuebner approved these changes

2023-10-26 15:39 UTC, hanshuebner requested changes
related test fails

2023-10-26 19:30 UTC, jschmid1 commented
> related test fails

fixed

2023-10-27 07:07 UTC, hanshuebner approved these changes

2023-10-27 07:07 UTC, merged