chore(ci): notify cherry-pick
Kong/kong pull request #12009
Opened 2023-11-13 15:33 UTC by outsinre

### Summary

Add a workflow to notify CE2EE cherry-pick.

### Checklist

- [n/a] The Pull Request has tests
- [n/a] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [n/a] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* Add a workflow to notify CE2EE cherry-pick.

### Issue reference

Fix #_[KAG-2881]_

2023-11-14 06:28 UTC, dndx requested changes
Can we wait a little? @AndyZhang0707 is researching how we properly do change management, I don't think another Slack bot will solve all the issues, plus we have half a dozen Slack bots already.

It seems that making use of Jira would be a better idea than adding another Slack bot that people learn to ignore after a while.

2023-11-14 06:29 UTC, outsinre commented
> Can we wait a little? @AndyZhang0707 is researching how we properly do change management, I don't think another Slack bot will solve all the issues, plus we have half a dozen Slack bots already.
> 
> It seems that making use of Jira would be a better idea than adding another Slack bot that people learn to ignore after a while.

I will do a POC. If merge or not, let's wait for decisions.

2023-11-14 08:42 UTC, outsinre commented
Worth to do this rather than manually track it.

2023-11-14 10:12 UTC, dndx requested changes
We are questioning the effectiveness of another Slack bot since previous ones were left ignored after a while. Please DO NOT merge until this is fully discussed.

2023-11-15 07:43 UTC, outsinre commented
@dndx This is ready for merge if wanted. Let's leave it here.

I will fix other workflows.

2023-12-06 07:22 UTC, closed without merging