Backport 11900 to release/2.8.x
Kong/kong pull request #12041
Opened 2023-11-16 05:46 UTC by chobits

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Full changelog

* [Implement ...]

### Issue reference

Fix #_[issue number]_

2023-11-16 06:33 UTC, ADD-SP approved these changes

2023-11-16 06:34 UTC, ADD-SP requested changes
CI is read

2023-11-16 06:56 UTC, outsinre commented
Please double-check this on `2.8.x.x`. According to customer reports, `2.8` does not have DNS issue. Pay attention to code base diff.

2023-11-17 09:56 UTC, chobits commented
> Please double-check this on `2.8.x.x`. According to customer reports, `2.8` does not have DNS issue. Pay attention to code base diff.

Talked with datong, this is a potential critical problem in 2.8.x, so we need to advance the merging process.

2023-11-17 10:02 UTC, ADD-SP approved these changes

2023-11-22 12:55 UTC, hanshuebner approved these changes

2023-11-24 08:48 UTC, merged