tests(*): use `.test` domain in most of the tests
Kong/kong pull request #12152
Opened 2023-12-04 10:02 UTC by catbro666

### Summary

Following Vinicius's [advocation](https://github.com/Kong/kong-ee/pull/7467#discussion_r1410706385), change most of urls in the tests to use `.test` domain to avoid external influencies. [Ref](https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml)

Except:
- `example`, `example.com`, `example.net`, `example.org`
- tests that are used to verify the format, validity or wildcard of the url itself (sni/router related tests), to prevent inadvertent change of the test logic
- real external urls that may be accessed (service host, dns/balancer related tests)
- some urls that are not sure if they will be accessed or not

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

2023-12-04 21:17 UTC, gszr requested changes

2023-12-04 21:17 UTC, gszr commented on spec/01-unit/19-hybrid/03-compat_spec.lua
> +            host = "example.com",
This one got inverted - I think this is the only case.

2023-12-05 12:40 UTC, locao approved these changes
Thank you for fixing this!
Out of curiosity I tested a few of the ones removed and you wouldn't believe how many of these actually existed.

2023-12-05 19:19 UTC, gszr approved these changes

2023-12-05 19:20 UTC, merged