fix(globalpatches): support exptime in SharedDict:set() api
Kong/kong pull request #12173
Opened 2023-12-07 10:38 UTC by chobits

This commit introduces support for the exptime parameter in SharedDict:set() to align its functionality with that of the original ngx.shared.DICT.set(). And it refines the logic of SharedDict:add() by using SharedDict:set().

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

2023-12-07 10:38 UTC, chobits commented
This pr will fix the test case failure of https://github.com/Kong/kong/pull/12100/files

2023-12-08 01:43 UTC, ADD-SP requested changes

2023-12-08 01:43 UTC, ADD-SP commented on changelog/unreleased/kong/fix-cli-shdict-set-api.yml
I think this is not a user-facing change.

2023-12-08 02:43 UTC, ADD-SP approved these changes

2023-12-08 02:45 UTC, Water-Melon approved these changes

2023-12-08 05:39 UTC, merged