fix(plugins/request-transformer): always lower when set header value
Kong/kong pull request #12289
Opened 2024-01-04 02:18 UTC by chronolaw

### Summary

KAG-3462

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

2024-01-04 06:41 UTC, ADD-SP requested changes
@StarlightIbuki We need to re-implement this PR: https://github.com/Kong/kong/pull/12244.

2024-01-04 06:41 UTC, ADD-SP commented on changelog/unreleased/kong/fix-request-transformer-rename-header.yml
This bug was introduced by https://github.com/Kong/kong/pull/12244, which has not been released yet, so the changelog is not needed.

2024-01-04 06:52 UTC, chronolaw commented on changelog/unreleased/kong/fix-request-transformer-rename-header.yml
done, thanks.

2024-01-05 02:23 UTC, chronolaw commented
We will revert #12244 then fix this flakiness.

2024-01-05 02:23 UTC, closed without merging