fix(core): fix an issue where Kong do not handle properly when Python and Javascript plugin server crashes
Kong/kong pull request #12582
Opened 2024-02-19 08:24 UTC by StarlightIbuki

### Summary

The bug was introduced when refactoring/cherry-picking. We missed the `mp_rpc.lua`. The PR also syncs the changes made to EE branches.

**DO NOT CHEERY-PICK THIS TO EE**.

### Checklist

- [N/A] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [N/A] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #12364

2024-02-19 08:30 UTC, ADD-SP approved these changes

2024-02-19 08:43 UTC, ms2008 commented on kong/runloop/plugin_servers/pb_rpc.lua
> +  kong.log.debug("started plugin server: seq ", conf.__seq__, ", worker ", ngx.worker.id(), ", instance id ",
Please keep the `or -1` here, as `ngx.worker.id()` returns `nil` for privileged workers. We've changed all parts of the codebase, so please be consistent.

Ref: https://github.com/Kong/kong/pull/12385

2024-02-19 15:01 UTC, gszr approved these changes
Good catch. I have the same changes over here in my wip branch: https://github.com/Kong/kong/commit/55586c1ce380688f2511aebbd98dda7c1d76bc4d. Let's merge this one and I will rebase mine 👍🏻

2024-02-19 15:02 UTC, gszr commented on changelog/unreleased/kong/plugin_server_restart.yml
> +message: "**Plugin Server**: fix an issue where Kong do not handle properly when Python and Javascript plugin server crashes"
```suggestion
message: "**Plugin Server**: fix an issue where Kong fails to properly restart MessagePack-based pluginservers (used in Python and Javascript plugins, for example)"
```

2024-02-19 15:03 UTC, gszr requested changes

2024-02-19 15:03 UTC, gszr commented on changelog/unreleased/kong/plugin_server_restart.yml
> +message: "**Plugin Server**: fix an issue where Kong do not handle properly when Python and Javascript plugin server crashes"
Good to merge after this change ^

2024-02-20 03:18 UTC, ms2008 approved these changes

2024-02-20 12:52 UTC, gszr approved these changes

2024-02-20 12:53 UTC, merged

2024-02-20 13:00 UTC, gszr commented
@StarlightIbuki - please open the remaining PRs on the kong-ee side, fixing the log line divergence.

2024-02-21 02:37 UTC, StarlightIbuki commented
> @StarlightIbuki - please open the remaining PRs on the kong-ee side, fixing the log line divergence. Also consider fixing this one [55586c1#diff-898289fc808a047bf9f9401e7e7b38625131477da1363ce4f68719a3dd9d6dec](https://github.com/Kong/kong/commit/55586c1ce380688f2511aebbd98dda7c1d76bc4d#diff-898289fc808a047bf9f9401e7e7b38625131477da1363ce4f68719a3dd9d6dec)

Do we have a PR for this branch? Or is it still WIP?

2024-02-23 11:18 UTC, gszr commented
> > @StarlightIbuki - please open the remaining PRs on the kong-ee side, fixing the log line divergence. Also consider fixing this one [55586c1#diff-898289fc808a047bf9f9401e7e7b38625131477da1363ce4f68719a3dd9d6dec](https://github.com/Kong/kong/commit/55586c1ce380688f2511aebbd98dda7c1d76bc4d#diff-898289fc808a047bf9f9401e7e7b38625131477da1363ce4f68719a3dd9d6dec)
> 
> Do we have a PR for this branch? Or is it still WIP?

Still wip. I will rebase it.