refactor(db/schema): ensure to validate possible routes fields
Kong/kong pull request #12681
Opened 2024-03-04 04:32 UTC by chronolaw

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

2024-03-04 04:58 UTC, chronolaw commented
blocked by #12650

2024-03-07 06:19 UTC, ADD-SP requested changes

2024-03-07 06:19 UTC, ADD-SP commented on changelog/unreleased/kong/fix-snis-tls-passthrough-in-trad-compat.yml
> +  Fix an issue where SNI-based routing does not work
``` suggestion
  Fixed an issue where SNI-based routing does not work
```

2024-03-08 08:54 UTC, ADD-SP approved these changes

2024-03-13 07:40 UTC, chobits approved these changes

2024-03-13 07:52 UTC, merged