tests(*): fix an error in http_mock template
Kong/kong pull request #12753
Opened 2024-03-18 15:04 UTC by outsinre

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[FTI-5807]_

2024-03-19 02:42 UTC, StarlightIbuki commented
Oops!
We need also to check if we use the name in tests and fix them.
Also, my original intention was to name them following the phase handlers so `header_filter` and `body_filter` should be the right name.

2024-03-19 02:53 UTC, outsinre commented
Another inconsistency:

https://github.com/Kong/kong/blob/master/spec/helpers/http_mock.lua#L85C41-L89 and https://github.com/Kong/kong/blob/master/spec/helpers/http_mock/template.lua#L143.

2024-03-19 03:02 UTC, StarlightIbuki commented
> Another inconsistency:
> 
> [`master`/spec/helpers/http_mock.lua#L85C41-L89](https://github.com/Kong/kong/blob/master/spec/helpers/http_mock.lua?rgh-link-date=2024-03-19T02%3A53%3A34Z#L85C41-L89) and [`master`/spec/helpers/http_mock/template.lua#L143](https://github.com/Kong/kong/blob/master/spec/helpers/http_mock/template.lua?rgh-link-date=2024-03-19T02%3A53%3A34Z#L143).

That's an outdated comment issue. Please fix them together.

2024-03-19 15:14 UTC, hanshuebner requested changes
Please fix the PR title and description.  What is the problem?  How is it fixed?

2024-03-20 02:29 UTC, outsinre commented
As this is not an urgent task, will come back after `3.7.0` PR.

2025-01-08 09:44 UTC, closed without merging