fix(plugins): compatibility with older data planes
Kong/kong pull request #12794
Opened 2024-03-27 16:42 UTC by samugi

### Summary

added compatibility with older data planes for the new tracing headers propagation configuration options

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/README.md)
- [x] (no) There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

KAG-4139

2024-03-28 05:37 UTC, ADD-SP requested changes

2024-03-28 05:37 UTC, ADD-SP commented on changelog/unreleased/kong/tracing-headers-propag-compat.yml
We haven't released this bug, so the changelog is not needed.

2024-03-28 09:09 UTC, samugi commented on changelog/unreleased/kong/tracing-headers-propag-compat.yml
true :)

2024-03-29 09:07 UTC, StarlightIbuki approved these changes

2024-03-29 09:10 UTC, StarlightIbuki commented
I wonder if the CI checker reminded us that schema changes need a corresponding change to the compatibility logic.

2024-03-29 11:46 UTC, samugi commented
> I wonder if the CI checker reminded us that schema changes need a corresponding change to the compatibility logic.

we'd probably need some smart check that detects **additions** of **required** fields and fail a workflow (or similar) otherwise we would end up with noisy reminders and eventually get used to ignoring them.

2024-03-29 11:54 UTC, ADD-SP approved these changes

2024-03-29 15:22 UTC, merged