fix(AI-Proxy): improve the robustness of anthropic's statistics
Kong/kong pull request #12854
Opened 2024-04-12 03:53 UTC by liverpool8056

There is a bit difference in the usage data between ai providers, and considering the variability of it, this PR attempts to improve the robustness during the process of transforming the usage data when: 
1. no usage data provided in the upstream response;
2. some possible changes in usage data in the future;

2024-04-16 08:39 UTC, hanshuebner requested changes

2024-04-16 08:39 UTC, hanshuebner commented on kong/llm/drivers/anthropic.lua
> +        } or "no usage data returned from upstream",
The code is too noisy with nested `and`/`or`.  Suggest to construct the `usage` table outside of the `res` table.

2024-04-16 10:49 UTC, hanshuebner approved these changes

2024-04-22 05:23 UTC, windmgc approved these changes

2024-04-22 06:07 UTC, merged