fix(ai-proxy): RC2 feedback
Kong/kong pull request #13000
Opened 2024-05-08 21:28 UTC by tysoekong

### Summary

Minor fix rollup from RC2, for edge-case usage from a new community user.

This can wait for 3.7.1, but creating PR so it isn't lost for later release.
### Checklist

- [ ] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE
### Issue reference

2024-05-08 21:29 UTC, tysoekong commented
Happy 13,000th pull request!!

2024-06-03 10:03 UTC, ttyS0e commented on kong/llm/drivers/shared.lua
> +    request.temperature = options.temperature or request.temperature
For reviewers - this is a mistake in 3.7.0, and should be the other way round.

2024-06-04 10:52 UTC, fffonion commented
changes look fine, the commit message as well the linked ticket description should be more descriptive, let's describe what's actually being fixed instead of `RC2 feedback`.

2024-06-07 15:12 UTC, fffonion commented
@tysoekong please resolve conflict

2024-06-07 15:29 UTC, ttyS0e commented
I just have to also investigate the streaming issue, it would make no sense to leave unpatched.

2024-06-11 05:40 UTC, fffonion approved these changes
merge on CI pass.
reviewers please review each commits individually

2024-06-12 02:30 UTC, vm-001 requested changes

2024-06-12 02:30 UTC, vm-001 commented on changelog/unreleased/kong/ai-proxy-azure-streaming copy.yml
Let's rename the file to make it more appropriate

2024-06-12 02:36 UTC, vm-001 commented on changelog/unreleased/kong/ai-proxy-azure-streaming copy.yml
> +  **AI-proxy-plugin**: Fix a bug where setting OpenAI SDK model parameter "null" caused analytics
Use a past tense Fixed. (@outsinre please correct me if I'm wrong)

2024-06-12 02:43 UTC, vm-001 commented on kong/llm/drivers/anthropic.lua
> +    messages.temperature = (model.options and model.options.temperature) or request_table.temperature or nil
or nil can be omitted
```
> v = a or b or nil
> print(v)
nil
```

2024-06-12 02:43 UTC, vm-001 commented on kong/llm/drivers/anthropic.lua
> +    messages.temperature = (model.options and model.options.temperature) or request_table.temperature or nil
and the following places

2024-06-12 02:43 UTC, vm-001 commented on kong/llm/drivers/cohere.lua
> +  if conf.model.options and conf.model.options.upstream_url then
can `conf.model` be nil?

2024-06-12 07:16 UTC, catbro666 commented on kong/plugins/ai-proxy/handler.lua
> +    if request_table.model ~= cjson.null then
How about checking `type(request_table.model) == "string"`

2024-06-17 14:30 UTC, tysoekong commented on kong/llm/drivers/cohere.lua
> +  if conf.model.options and conf.model.options.upstream_url then
No it MUST have a provider set.

2024-06-18 09:21 UTC, tysoekong commented on changelog/unreleased/kong/ai-proxy-azure-streaming copy.yml
It was a mistake, I fixed it.

2024-06-18 09:21 UTC, tysoekong commented on changelog/unreleased/kong/ai-proxy-azure-streaming copy.yml
> +  **AI-proxy-plugin**: Fix a bug where setting OpenAI SDK model parameter "null" caused analytics
Fixed all these.

2024-06-18 10:29 UTC, tysoekong commented on kong/llm/drivers/anthropic.lua
> +    messages.temperature = (model.options and model.options.temperature) or request_table.temperature or nil
I've fixed all these.

2024-06-18 10:30 UTC, tysoekong commented on kong/plugins/ai-proxy/handler.lua
> +    if request_table.model ~= cjson.null then
I changed to check the type as just string, and then check for empty later (which is 'allowed') also.

2024-06-18 11:00 UTC, tysoekong commented
READY TO GO

2024-06-18 12:54 UTC, fffonion approved these changes
moving forward, we might want to setup a SSE server to catch more more corner cases

2024-06-19 02:09 UTC, liverpool8056 approved these changes

2024-06-19 03:14 UTC, vm-001 approved these changes

2024-06-20 01:48 UTC, merged