refactor(balancer): get headers as hash identifier by ngx.var
Kong/kong pull request #13063
Opened 2024-05-23 08:28 UTC by chronolaw

### Summary

Before this PR we use `ngx.req.get_headers()` to get all possible header values as identifier,
but since nginx 1.23.0 or OpenResty  1.25.3.1 `ngx.var` can get a combined value for all header values 
with identical name (joined by comma), so I think that we could simplify these code. 

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

2024-05-29 07:05 UTC, oowl commented on kong/runloop/balancer/init.lua
> +      -- ngx.var will automatically combine all header values with identical name
Can you give us a URL to verify it?

2024-05-29 07:33 UTC, chronolaw commented on kong/runloop/balancer/init.lua
> +      -- ngx.var will automatically combine all header values with identical name
This PR has added a test case for it.

2024-05-29 09:19 UTC, oowl approved these changes

2024-05-29 09:19 UTC, oowl commented on kong/runloop/balancer/init.lua
> +      -- ngx.var will automatically combine all header values with identical name
OK, gotcha!

2024-05-29 14:42 UTC, bungle commented
@chronolaw please use this instead and pass the `ctx` that is already there:
https://github.com/Kong/kong/blob/master/kong/tools/http.lua#L533

2024-05-29 14:43 UTC, bungle requested changes
see above

2024-05-29 14:47 UTC, bungle approved these changes

2024-05-30 01:37 UTC, ADD-SP approved these changes

2024-05-30 01:37 UTC, merged