style(runloop/wasm): style clean with early return
Kong/kong pull request #13078
Opened 2024-05-24 02:56 UTC by chronolaw

### Summary

style clean with early return

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

2024-05-31 16:19 UTC, bungle requested changes
Just how I see this.

2024-05-31 16:19 UTC, bungle commented on kong/runloop/wasm.lua
> +    return routes and routes[route_id]
I would probably prefer `if..elseif..else` but you can remove the local ref at the top and return ref at the bottom.

2024-05-31 16:19 UTC, bungle commented on kong/runloop/wasm.lua
> +  if typ == TYPE_COMBINED then
Here I think the original was better.

2024-06-01 12:30 UTC, chronolaw commented
Since it is only a style clean, if we think the original is better then we need not to change them.

2024-06-01 12:30 UTC, closed without merging