fix(cmd): fix kong cli not printing some debug level error log
Kong/kong pull request #13143
Opened 2024-06-03 07:45 UTC by windmgc

### Summary

This PR fixes a problem that running `kong` CLI command will not print some of the debug level error logs. Those error logs may be triggered by `ngx.log` before the actual `kong.cmd` module gets called. 

### Checklist

- [x] The Pull Request has tests
- [x] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

The issue in this PR was discovered when debugging FTI-5995, but it is not related to the ticket's problem at all.

2024-06-03 17:30 UTC, flrgh approved these changes
LGTM :+1:

2024-06-04 01:51 UTC, ADD-SP approved these changes

2024-06-04 02:11 UTC, ADD-SP requested changes

2024-06-04 02:11 UTC, ADD-SP commented on spec/02-integration/02-cmd/16-verbose_spec.lua
Looks like this test is stuck for 5hours, please investigate.

https://github.com/Kong/kong/actions/runs/9346252834/job/25764525806?pr=13143

2024-06-04 03:29 UTC, windmgc commented on spec/02-integration/02-cmd/16-verbose_spec.lua
Weird, it works on my machine.

Let me dig a bit

2024-06-04 09:24 UTC, windmgc commented on spec/02-integration/02-cmd/16-verbose_spec.lua
I sshed onto the runner machine and ran the tests manually; it turns out that the `kong version --vv` command is stuck on the syscall to write debug level error logs to stderr: 

```
write(2, "2024/06/04 08:51:34 [debug] 1896"..., 72
```

And the process is at a status of

```
runner    189647  189645  0 08:51 pts/0    00:00:00 nginx: process is shutting down
```

It seems like the process's stderr buffer is full and waiting for someone to read its buffer to let it free...
That makes me wonder if there is any issue inside `resty.shell` or `ngx.pipe`.

However, if I run `kong version --vv` in a shell, it can execute without any problem, and print the proper logs. And I cannot reproduce it on a Ubuntu machine with debug enabled(which generates tons of error logs during runtime).

I'm still trying to find the reason of it

2024-06-04 10:00 UTC, ADD-SP commented on spec/02-integration/02-cmd/16-verbose_spec.lua
Maybe @Water-Melon has some knowledge about this kind of issue.

2024-06-05 05:27 UTC, windmgc commented on spec/02-integration/02-cmd/16-verbose_spec.lua
Thanks to @Water-Melon for the quick fix! https://github.com/Kong/kong/pull/13163

2024-06-05 06:18 UTC, ADD-SP approved these changes

2024-06-05 06:23 UTC, merged