refactor(tools/rand): speed up random string generation
Kong/kong pull request #13150
Opened 2024-06-04 00:32 UTC by chronolaw

### Summary

use `string.find` before `string.gsub`.

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

2024-06-04 00:35 UTC, chronolaw commented
A simple performance test:
```
      it("#only random string test", function()
        ngx.update_time()
        local t = ngx.now()

        for i = 1, 100*1000 do
          utils.random_string()
        end

        ngx.update_time()
        print("time is ", ngx.now() - t)
      end)
```
the result of master: 0.20499992370605
the result of this PR: 0.16400003433228

This PR is about 20% faster than the master.

2024-06-04 01:49 UTC, ADD-SP approved these changes

2024-06-04 09:24 UTC, fffonion commented
If the string is not CSRNG at first, we can just use math.random
```
local abc = {"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","r","s","t","u","v","z","y","w","q","1","2","3","4","5","6","7","8","9","0"}
local string = table.new(32, 0)
local function GeneratedString()
    table.clear(string)
    for i=1,32 do
        local rdm = math.random(1,35)
        string[i] = abc[rdm]
    end
    return table.concat(string, "")
end
```
this one is fastest


<details>

```lua
local ffi = require "ffi"


local C             = ffi.C
local ffi_new       = ffi.new
local encode_base64 = ngx.encode_base64
local char = string.char
local rand = math.random


ffi.cdef[[
typedef unsigned char u_char;

int RAND_bytes(u_char *buf, int num);

unsigned long ERR_get_error(void);
void ERR_load_crypto_strings(void);
void ERR_free_strings(void);

const char *ERR_reason_error_string(unsigned long e);

int open(const char * filename, int flags, ...);
size_t read(int fd, void *buf, size_t count);
int write(int fd, const void *ptr, int numbytes);
int close(int fd);
char *strerror(int errnum);
]]


local _M = {}


local get_rand_bytes
do
  local ngx_log = ngx.log
  local WARN    = ngx.WARN

  local ffi_fill    = ffi.fill
  local ffi_str     = ffi.string
  local bytes_buf_t = ffi.typeof "char[?]"

  local function urandom_bytes(buf, size)
    local fd = C.open("/dev/urandom", O_RDONLY, 0) -- mode is ignored
    if fd < 0 then
      ngx_log(WARN, "Error opening random fd: ",
                    ffi_str(C.strerror(ffi.errno())))

      return false
    end

    local res = C.read(fd, buf, size)
    if res <= 0 then
      ngx_log(WARN, "Error reading from urandom: ",
                    ffi_str(C.strerror(ffi.errno())))

      return false
    end

    if C.close(fd) ~= 0 then
      ngx_log(WARN, "Error closing urandom: ",
                    ffi_str(C.strerror(ffi.errno())))
    end

    return true
  end

  -- try to get n_bytes of CSPRNG data, first via /dev/urandom,
  -- and then falling back to OpenSSL if necessary
  get_rand_bytes = function(n_bytes, urandom)
    local buf = ffi_new(bytes_buf_t, n_bytes)
    ffi_fill(buf, n_bytes, 0x0)

    -- only read from urandom if we were explicitly asked
    if urandom then
      local rc = urandom_bytes(buf, n_bytes)

      -- if the read of urandom was successful, we returned true
      -- and buf is filled with our bytes, so return it as a string
      if rc then
        return ffi_str(buf, n_bytes)
      end
    end

    if C.RAND_bytes(buf, n_bytes) == 0 then
      -- get error code
      local err_code = C.ERR_get_error()
      if err_code == 0 then
        return nil, "could not get SSL error code from the queue"
      end

      -- get human-readable error string
      C.ERR_load_crypto_strings()
      local err = C.ERR_reason_error_string(err_code)
      C.ERR_free_strings()

      return nil, "could not get random bytes (" ..
                  "reason:" .. ffi_str(err) .. ") "
    end

    return ffi_str(buf, n_bytes)
  end
end

math.randomseed(os.clock() ^ 5)
local sets = {{97, 122}, {65, 90}, {48, 57}} -- a-z, A-Z, 0-9
local function string_random(chars)
        local str = ""
        for i = 1, chars do
                local charset = sets[ math.random(1, #sets) ]
                str = str .. string.char(math.random(charset[1], charset[2]))
        end
        return str
end
abc = {"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","r","s","t","u","v","z","y","w","q","1","2","3","4","5","6","7","8","9","0"}
local string = table.new(32, 0)
local function GeneratedString()
    table.clear(string)
    for i=1,32 do
        local rdm = math.random(1,35)
        string[i] = abc[rdm]
    end
    return table.concat(string, "")
end

local t = ngx.now()
local function timeit()
    ngx.update_time()
    local tt = ngx.now()
    local elapsed = tt - t
    t = tt
    return elapsed
end
local ITER = 10000

local random_string = function()
    -- get 24 bytes, which will return a 32 char string after encoding
    -- this is done in attempt to maintain backwards compatibility as
    -- much as possible while improving the strength of this function
    local str = encode_base64(get_rand_bytes(24, false))

    if str:find("/", 1, true) then
      str = str:gsub("/", char(rand(48, 57)))  -- 0 - 10
    end

    if str:find("+", 1, true) then
      str = str:gsub("+", char(rand(65, 90)))  -- A - Z
    end

    if str:find("=", 1, true) then
      str = str:gsub("=", char(rand(97, 122))) -- a - z
    end

    return str
  end

timeit()
for i = 1, ITER do
    random_string()
end
print(timeit())
print(random_string())

timeit()
for i = 1, ITER do
    string_random(32)
end
print(timeit())
print(string_random(32))

timeit()
for i = 1, ITER do
    GeneratedString()
end
print(timeit())
print(GeneratedString())
```
</details>

2024-06-04 09:29 UTC, chronolaw commented
@fffonion , It may be a big change, we will try it in another PR.

2024-06-04 09:39 UTC, bungle requested changes
Some even faster ways of doing this.

2024-06-04 09:39 UTC, bungle commented on kong/tools/rand.lua
> +    return str
Probably something like:
```lua
return encode_base58(get_rand_bytes(24, true))
```

would be the fastest.

Or doing:
```lua
local byte = string.byte
local OUTPUT = require("string.buffer").new(32)
local SLASH_BYTE = byte("/")
local PLUS_BYTE = byte("+")
local EQ_BYTE = byte("=")
random_string = function()
  local str = encode_base64(get_rand_bytes(24, true))
  for i=1, 32 do
    OUTPUT:reset()
    local b = byte(str, i) 
    if b == SLASH_BYTE then
      OUTPUT:putf("%c", rand(48, 57))
    elseif b == PLUS_BYTE then
      OUTPUT:putf("%c", rand(65, 90))
    elseif b == EQ_BYTE then
      OUTPUT:putf("%c", rand(97, 122))
    else
      OUTPUT:putf("%c", b)
    end
  end
  str = OUTPUT:get()
  return str
end

2024-06-04 09:49 UTC, bungle commented on kong/tools/rand.lua
> +    return str
Actually even faster:
```
local byte = string.byte
local OUTPUT = require("string.buffer").new(32)
local SLASH_BYTE = byte("/")
local PLUS_BYTE = byte("+")
random_string = function()
  OUTPUT:reset()
  local str = encode_base64(get_rand_bytes(24, true), true)
  for i = 1, 32 do
    local b = byte(str, i) 
    if b == SLASH_BYTE then
      OUTPUT:putf("%c", rand(48, 57))
    elseif b == PLUS_BYTE then
      OUTPUT:putf("%c", rand(65, 90))
    else
      OUTPUT:putf("%c", b)
    end
  end
  str = OUTPUT:get()
  return str
end

2024-06-04 14:26 UTC, fffonion commented
It also seems reading from /dev/urandom is slower than using openssl rand bytes itself.

2024-06-04 21:56 UTC, bungle commented on kong/tools/rand.lua
> +    return str
This is another alternative, but it is as fast as above:
```lua
local byte = string.byte
local OUTPUT = require("string.buffer").new(32)
local ALNUM = {
  "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
  "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
  "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
}
local function random_string()
  OUTPUT:reset()
  local str = get_rand_bytes(32, true)
  for i = 1, 32 do
    OUTPUT:put(ALNUM[byte(str, i) % 58 + 1])
  end
  str = OUTPUT:get()
  return str
end
```

2024-06-04 22:02 UTC, bungle commented
> It also seems reading from /dev/urandom is slower than using openssl rand bytes itself. It feels to me that reading from /dev/urandom is just not worth as it creates a less secure random bytes and it's slower too.

Here is the original related commit:
https://github.com/Kong/kong/commit/c01752a8a0620e141d907a0d46e60b67f0e0c97c

2024-06-05 02:03 UTC, chronolaw commented
These discussion seems to be out of this PR's scope, if we want to change the algorithm of random, should we create a ticket?

2024-06-05 06:19 UTC, chronolaw commented
I tried one suggestion (OUTPUT + ALNUM) in the same test, the result is `0.15100002288818`,
It looks like that we don't get too much improvement on performance.

2024-06-05 07:57 UTC, bungle commented
> I tried one suggestion (OUTPUT + ALNUM) in the same test, the result is `0.15100002288818`, It looks like that we don't get too much improvement on performance.

Yes, but those are more linear than yours, which is good.

So far either this:
https://github.com/Kong/kong/pull/13150#discussion_r1625705881
OR
https://github.com/Kong/kong/pull/13150#discussion_r1626647187

Looks the best.

2024-06-05 08:05 UTC, bungle commented
> It feels to me that reading from /dev/urandom is just not worth as it creates a less secure random bytes and it's slower too.

I'd like to read some reference where does it create `less secure random bytes`? Also how much slower it is?

2024-06-05 08:12 UTC, bungle commented on kong/tools/rand.lua
> +    return str
Here is one without string buffer:
```lua
local byte = string.byte
local concat = table.concat
local OUTPUT = { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "0", "1", "2", "3", "4", "5", }
local ALNUM = {
  "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
  "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
  "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",                                                                                                                                                                                                                                  
}
                                                                                                                                                                                                                                  
local function random_string()
  local str = get_rand_bytes(32, true)
  for i = 1, 32 do
    OUTPUT[i] = ALNUM[byte(str, i) % 62 + 1]
  end
  str = concat(OUTPUT)
  return str
end
```

2024-06-05 08:20 UTC, chronolaw commented
I removed `str:find("=", 1, true)`, but do not find significant performance improvement.

Perhaps we could keep it and make this `randome_string()` to a more common functions (generate any length).

2024-06-05 08:22 UTC, bungle commented
> Perhaps we could keep it and make this `randome_string()`

Why keep it when it does nothing?

2024-06-05 08:28 UTC, chronolaw commented
This generates a 32 bytes random and a 44 bytes string. https://github.com/Kong/kong/blob/master/kong/plugins/session/schema.lua#L56

2024-06-05 20:05 UTC, bungle commented
> This generates a 32 bytes random and a 44 bytes string. https://github.com/Kong/kong/blob/master/kong/plugins/session/schema.lua#L56

Then we can just generate more random bytes so that padding doesn't happen.

2024-06-06 01:01 UTC, chronolaw commented
I removed `gsub(str, "=", rand)`. For other optimization suggestions I think we can open a new perf PR.

2024-06-07 10:14 UTC, bungle commented
> I removed `gsub(str, "=", rand)`. For other optimization suggestions I think we can open a new perf PR.

@chronolaw, here it is: https://github.com/Kong/kong/pull/13186

So this PR can be now closed?

2024-06-07 10:50 UTC, closed without merging

2024-06-11 08:45 UTC, fffonion commented
>  feels to me that reading from /dev/urandom is just not worth as it creates a less secure random bytes and it's slower too.

I'm not referring the openssl rand_bytes vs. /dev/urandom is securer or weaker, but it depends on our usage.
There are three points makes read from /dev/urandom + base64 not a good design:
- We have to use math.rand to map extra character range `+`, `/`, thus the output is a mix of cryptographic secure source and non cryptographic secure source.
- In our code, we have places we just need random strings, thus it doesn't have to be CSPRNG. We can just use math.random to generate fast and non cryptographic secure random strings.
- Use of /dev/urandom is not FIPS compliant (unless the OS itself is FIPS compliant), as it uses non approved algorithm, if the output is used as secret.

So I'm just suggesting to have a pure lua math.rand flavor and a openssl rand bytes variant (no encode_base64, just use to_hex) to `random_string`.