Update SECURITY.md and made it more detailed
Kong/kong pull request #13360
Opened 2024-07-10 16:50 UTC by QuicksilverYT

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

2024-07-10 16:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=13360) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=13360) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=13360) it.</sub>

2024-07-12 03:13 UTC, outsinre approved these changes

2024-07-12 03:32 UTC, hanshuebner requested changes
Awaiting confirmation from our security team.

2024-07-12 13:21 UTC, hanshuebner commented
This PR does not reflect Kong's security policy and therefore won't be merged.

2024-07-12 13:21 UTC, closed without merging