feat(ai-proxy): add option to return model name in response header
Kong/kong pull request #13472
Opened 2024-08-08 09:28 UTC by fffonion

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

2024-08-08 09:43 UTC, oowl approved these changes

2024-08-09 02:04 UTC, liverpool8056 requested changes

2024-08-09 07:28 UTC, fffonion commented on kong/llm/proxy/handler.lua
> +    local name = conf.model.provider .. "/" .. (kong.ctx.plugin.llm_model_requested or conf.model.name)
yes, `model.name` can be overriden by request, but not `model.provider`.

2024-08-09 07:29 UTC, fffonion commented on spec/02-integration/09-hybrid_mode/09-config-compat_spec.lua
> +      it("[ai-proxy] tries to use unsupported providers on older Kong versions #ttt", function()
yes, my fault

2024-08-09 07:29 UTC, StarlightIbuki requested changes

2024-08-09 07:29 UTC, StarlightIbuki commented on kong/clustering/compat/removed_fields.lua
> +      "model_header_name",
`model_name_header` or `model_header_name`?

2024-08-09 07:38 UTC, StarlightIbuki approved these changes

2024-08-09 08:01 UTC, liverpool8056 approved these changes

2024-08-09 08:03 UTC, merged

2024-08-09 08:04 UTC, fffonion commented
will do cherrypick as part of https://github.com/Kong/kong-ee/pull/9912