Minor bug fix: Fix error message for `retries`
Kong/kong pull request #13605
Opened 2024-09-02 13:50 UTC by AD7six

### Summary

Fix this error message which refers to the wrong variable:

```
if retries < 0 or retries > 32767 then
      error("port must be an integer between 0 and 32767: given " .. retries, 2)
```

### Checklist

- [X] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

This is an unreported bug.

2024-09-02 13:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=13605) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=13605) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=13605) it.</sub>

2024-09-12 02:44 UTC, liverpool8056 commented
@AD7six good catch. Please add a changelog under changelog/unrelease/kong

2024-09-12 07:34 UTC, AD7six commented
Sure thing. Here's another minor bug I noticed along the way :) https://github.com/Kong/kong/pull/13658

2024-09-13 03:44 UTC, liverpool8056 requested changes

2024-09-13 03:44 UTC, liverpool8056 commented on changelog/unreleased/kong/fix-retries-error-message.yml
> +scope: Core
```suggestion
scope: PDK
```

2024-09-18 02:08 UTC, liverpool8056 approved these changes

2024-10-11 10:04 UTC, AD7six commented
@liverpool8056 👋 what is required to get this MR merged :) ?

2024-10-11 12:37 UTC, gszr approved these changes
Nice catch!

2024-10-11 12:38 UTC, gszr commented
Thanks for your first contribution, @AD7six! Here's to many more 🦍

2024-10-11 12:39 UTC, merged

2024-10-11 12:39 UTC, gszr commented
> @liverpool8056 👋 what is required to get this MR merged :) ?
> 
> If it's waiting for some action from me - what is that action?

All PRs require two reviews : )