fix(response-ratelimiting): fix missing usage headers for upstream
Kong/kong pull request #13696
Opened 2024-09-20 06:08 UTC by t-yuki

### Summary
`response-ratelimiting` plugin should send usage headers to upstream server.
But in Kong 3.8, there are no usage headers such as `X-RateLimit-Remaining-Videos: 10` for upstream requests.

In this change, it coming back usage headers for upstream.

### Checklist

- [ ] The Pull Request has tests
   - It seems to be already there are tests for this feature but are there passing? https://github.com/Kong/kong/blob/master/spec/03-plugins/24-response-rate-limiting/04-access_spec.lua#L505
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #13682

2024-09-20 06:19 UTC, ADD-SP commented
@t-yuki Thanks for your contribution! Would you mind adding a regression test on this issue? I think we have missed this test for a long time.

2024-09-20 06:29 UTC, ADD-SP commented
Since this is a new issue introduced in 3.8 and should be a small fix, I added this to the 3.9 milestone.

2024-09-23 04:01 UTC, ADD-SP commented
@t-yuki Could you fix failure tests?

2024-11-18 21:44 UTC, gszr reviewed
Since this is touching a recent nontrivial [refactor](https://github.com/kong/kong/commit/3c0aa6097f1421e2d0bfd4bc7c8be8fa54a5b881#diff-e799a72960fa7f956455fff4cca7947749b5c6ecd7cb1e18f220931911eb0bcfR13), we should carefully verify it doesn't revert important bits of said refactor, fixing one but introducing other issues. cc @ADD-SP

2024-11-18 21:44 UTC, gszr commented on changelog/unreleased/kong/fix-response-ratelimiting-upstream-headers.yml
> +message: "**response-ratelimiting**: Fixed missing upstream headers."
```suggestion
message: "**response-ratelimiting**: ensure rate-limiting headers are sent upstream."
```

2025-01-07 06:42 UTC, ProBrian requested changes

2025-01-14 06:44 UTC, ProBrian commented on spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
> +local function wait(reset)
That's a good effort on making the tests more stable. However, we are doing refinement on the test cases, which is not just waiting for a longer time, we will rely on some status endpoint to make the waiting more reasonable and waiting time as short as possible.
So could you just make the functional changes, and revert the test spec changes? So that I could approve and merge your code. Much appreciates on your effort!

2025-01-20 01:54 UTC, ProBrian approved these changes

2025-01-21 01:38 UTC, t-yuki commented on spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
> +local function wait(reset)
OK, It's reverted. However, I'm not sure it passes the tests on CI environments. It never passes the tests in my local environment.

2025-01-21 02:28 UTC, ProBrian commented on spec/03-plugins/24-response-rate-limiting/04-access_spec.lua
> +local function wait(reset)
Thanks, I thinks you can leave the test name unchanged(keep the "flaky" in description), we will remove it after we make it stable.

2025-02-06 06:15 UTC, ADD-SP commented
Approved to run CIs against https://github.com/Kong/kong/pull/13696/files/b98da5efa4c8a70cb05725b9ea09c5ff680c8170.

2025-02-06 06:19 UTC, ADD-SP commented
CI is not started 🤔, no idea about the reason yet.

2025-02-06 08:35 UTC, ADD-SP approved these changes

2025-02-06 08:36 UTC, merged

2025-02-06 08:37 UTC, ADD-SP commented
@t-yuki Thanks for your contribution!

2026-10-23 14:20 UTC, ozsaygin commented
Hi @ADD-SP, this PR is labeled `backport release/3.9.x`, but the backport never happened. There's no bot comment, no `incomplete-backport` label and no backport PR, and neither 3.9.3 nor 3.9.4 has the fix. `kong/plugins/response-ratelimiting/access.lua` on `release/3.9.x` still sends `X-RateLimit-Remaining-<limit>` to the client instead of the upstream, even with `hide_client_headers` enabled.

Since master isn't released as OSS, no OSS release has this fix yet, and we're running it as a local patch on 3.9.3. Could it go into 3.9.5? `release/3.9.x` has already been bumped to 3.9.5. I can open the cherry-pick PR against `release/3.9.x` if that helps.