chore(ci): run ai assisted changelog reviews
Kong/kong pull request #13752
Opened 2024-10-14 15:12 UTC by jschmid1

### Summary

Use chatgpt to review changelog entries. We pass the title, description and the changelog itself. The action will create suggestions in form of a review.

![image](https://github.com/user-attachments/assets/23acde71-5040-4f33-94e6-7ca6a2e68957)

Code will not be sent to OpenAI. This action will only be triggered when a changelog file is present. To re-trigger it, remove the comment/review.

2024-10-15 08:22 UTC, samugi approved these changes

2024-10-15 10:37 UTC, nowNick approved these changes

2024-10-16 03:47 UTC, dndx requested changes
@curiositycasualty raised some concerns about the current integration in Slack, we should make sure these are addressed before merging.

2024-11-18 14:17 UTC, gszr commented
> @curiositycasualty raised some concerns about the current integration in Slack, we should make sure these are addressed before merging.

Can we get this merged and iterate later? Having it enabled only on EE creates divergence in changelogs. We often merge PRs in OSS to only later get ChatGPT-based suggestions, and those do not end up backported over here.

2024-11-18 14:17 UTC, gszr approved these changes

2025-12-09 19:42 UTC, closed without merging