feat(tracing): Add instana header support in propagation
Kong/kong pull request #13915
Opened 2024-11-23 19:52 UTC by SuzyWangIBMer

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[12494]_

2024-11-28 09:02 UTC, samugi reviewed
Thank you so much for this great contribution! A couple of notes:

- For consistency, this should be supported by the Zipkin plugin as well, which requires a small schema update similar to what was done for OpenTelemetry in this PR, and an integration test in `spec/03-plugins/34-zipkin/zipkin_spec.lua`.
- The test in `spec/01-unit/26-observability/02-propagation_strategies_spec.lua` should be updated as well to include this new header format

2024-11-28 16:05 UTC, SuzyWangIBMer commented on kong/observability/tracing/propagation/injectors/instana.lua
> +  end
if x-instana-l is not presented in the trace, instana assume its default value to be "1"

2024-11-28 16:09 UTC, SuzyWangIBMer commented on kong/observability/tracing/propagation/extractors/instana.lua
My understand is that it can have no instana headers at all, as long as "traceparent" is there, instana can read info from traceparent header. What would u suggest we do here?

2024-12-04 08:52 UTC, samugi commented on kong/observability/tracing/propagation/extractors/instana.lua
what I mean is, when `x-instana-*` headers are in the request, is any header required in order to make them valid?

Just as an example, in B3, [the specification says](https://github.com/openzipkin/b3-propagation):
* Unless propagating only the Sampling State, the X-B3-SpanId header is required.
* Unless propagating only the Sampling State, the X-B3-TraceId header is required.

so, in B3, you can pass either the `x-b3-sampled` header alone, or you have to pass all three headers to make the context extraction succeed.

This really depends on the Instana headers specification, from what I read [here](https://github.com/openzipkin/b3-propagation), it seems that only the `x-instana-l` header is optional, which means if a request has some Instana headers, but `x-instana-t` or `x-instana-s` are missing, the context extraction should fail and ignore the remaining headers. I am not familiar with Instana so I wanted to confirm the specification is reflected in the context extractor's logic here.

2024-12-17 08:51 UTC, samugi commented
In addition to my previous comment, this needs a rebase.

2025-01-08 19:32 UTC, SuzyWangIBMer commented on kong/observability/tracing/propagation/extractors/instana.lua
> +
I have updated `trace_id`, `span_id`, `level_id` variable name to `trace_id_raw`, `span_id_raw` and` level_id_raw`


Also since we dont use `correlation_type` and `correlationId` here, changed 

```
level_id_raw = level_id_raw:match("^([0-1])$") 
              or level_id_raw:match("^([0-1]),correlationType=(.-);correlationId=(.*)")
```

to 
```
  level_id_raw = level_id_raw:match("^([0-1])$") 
                or level_id_raw:match("^([0-1]).")
```

2025-01-14 09:11 UTC, samugi requested changes
Left a few comments.

Please also address my comments from the previous review:

- For consistency, this should be supported by the Zipkin plugin as well, which requires a small schema update similar to what was done for OpenTelemetry in this PR, and an integration test in spec/03-plugins/34-zipkin/zipkin_spec.lua.

- The test in spec/01-unit/26-observability/02-propagation_strategies_spec.lua should be updated as well to include this new header format

2025-01-14 09:11 UTC, samugi commented on kong/observability/tracing/propagation/extractors/instana.lua
> +  local level_id_raw = headers["x-instana-l"]
the value of `headers["name"]` can be a string or a table, depending on whether the same header was passed more than once in the request, see: https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxreqget_headers

We should handle the scenario where multiple headers are passed, for example by ignoring the header if passed more than once, or grabbing the first value.

2025-01-14 09:11 UTC, samugi commented on kong/observability/tracing/propagation/extractors/instana.lua
> +                or level_id_raw:match("^([0-1]).")
could we just:
```suggestion
    level_id_raw = level_id_raw:sub(1, 1)
```

2025-01-14 09:11 UTC, samugi commented on kong/observability/tracing/propagation/extractors/instana.lua
> +  local should_sample = level_id_raw or "1"
this must be type boolean, see [here](https://github.com/Kong/kong/blob/a61ef41091c38c0183d86dcdca502c06e971511d/kong/observability/tracing/propagation/extractors/_base.lua#L165)
```suggestion
  local should_sample = level_id_raw == "1"
```

2025-02-05 08:17 UTC, samugi reviewed
just a few minor comments, then it looks good to me.

2025-02-05 08:17 UTC, samugi commented on kong/observability/tracing/propagation/extractors/instana.lua
> +  if trace_id_raw then
this `if` is not needed, we know `type` is string by now, so it cannot be `nil`

2025-02-05 08:17 UTC, samugi commented on kong/observability/tracing/propagation/extractors/instana.lua
> +  if span_id_raw then
same as above

2025-02-05 08:17 UTC, samugi commented on kong/observability/tracing/propagation/extractors/instana.lua
> +  if level_id_raw then
same

2025-02-06 21:08 UTC, SuzyWangIBMer commented on kong/observability/tracing/propagation/extractors/instana.lua
> +  if level_id_raw then
We probably still need this one since level id can be nil.

2025-02-06 21:30 UTC, SuzyWangIBMer commented on kong/observability/tracing/propagation/extractors/instana.lua
> +  if trace_id_raw then
updated

2025-02-06 21:31 UTC, SuzyWangIBMer commented on kong/observability/tracing/propagation/extractors/instana.lua
> +  if span_id_raw then
updated

2025-02-10 12:57 UTC, samugi commented on kong/observability/tracing/propagation/extractors/instana.lua
> +  if level_id_raw then
oh yeah, sorry, ignore this comment

2025-02-19 20:53 UTC, samugi approved these changes

2025-02-25 15:03 UTC, nowNick approved these changes
Looks good to me! Great job @SuzyWangIBMer 🚀

2025-02-25 15:18 UTC, merged

2026-08-12 15:53 UTC, sriemer commented
@samugi @nowNick Can anyone of you explain me why this is still not part of a released Kong version?
I've tested Kong 3.9.3 and this is not included.
Can you help me to get this into a released Kong, please? TIA

Btw.: Suzy Wang is not with IBM/Instana anymore.

2026-08-12 16:12 UTC, sriemer commented
> Can anyone of you explain me why this is still not part of a released Kong version?

I see, this requires Kong >= 3.10.0 and therefore some Kong Gateway Enterprise version. :disappointed: