[draft] test pdk refine without patching all resty APIs
Kong/kong pull request #13981
Opened 2024-12-05 09:30 UTC by ProBrian

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix #_[issue number]_

2024-12-16 01:57 UTC, ProBrian commented on kong/globalpatches.lua
> +          read_req_body()
`ngx.req.read_body` only need to be called once in a request lifetime. Although multiple calls in the same request 
 don't re-read data to buffer multiple times, there are still some extra cost of check logic. So we could just avoid it to gain better performance.

2024-12-16 01:59 UTC, ProBrian commented on kong/pdk/request.lua
> +    return ngx.ctx.scheme or var.scheme
`ctx` is cheaper then `var`, so use `ctx` if exists, like what we do in router handling: `local req_scheme = ctx and ctx.scheme or var.scheme`

2024-12-16 02:00 UTC, ProBrian commented on kong/pdk/request.lua
> +  function _REQUEST.get_header(name, ctx)
`http_get_header` supports `ctx` param to cache headers, expose it to `get_header` API so we could use cache.

2024-12-16 02:03 UTC, ProBrian commented on kong/pdk/request.lua
> +    local content_type = mimetype or ngx.var.http_content_type
"Content-Type" is a built-in single value header, which means `ngx.var.http_content_type` always returns the same value of `get_header("Content-Type")`, and fetching single header by `ngx.var` is quicker than `get_header`(which may use `get_headers()["Content-Type"]` to get the single header).

2024-12-16 02:04 UTC, ProBrian commented on kong/pdk/service/response.lua
> +  function response.get_raw_body(buffered_proxying)
just a minor refinement so that if we could reduce the reads of `ngx.ctx.buffered_proxying` by passing it by param

2024-12-16 02:07 UTC, ProBrian commented on kong/plugins/basic-auth/access.lua
> +  local ctx = {}
Use a local `ctx` here which is cheaper than`ngx.ctx`, and the cache is only fresh in the local `ctx` lifetime, not in the request lifetime, so we don't need `ngx.ctx`

2025-01-10 15:19 UTC, bungle commented on kong/pdk/service/response.lua
> +    local buffered = buffered_proxying or ctx.buffered_proxying
I am not sure about that. Adding `buffered_proxying` as public interface parameter feels a bit wrong. Also what if someone passes `false` here?

2025-01-13 01:29 UTC, ProBrian commented on kong/pdk/service/response.lua
> +    local buffered = buffered_proxying or ctx.buffered_proxying
Yes this seems a little be confused if users pass in `false` but we will still respect the `ctx.bufferred_proxying`.
My intention was to reduce the read of `ctx`, because local variable is faster than `ctx`, and when invoke `get_raw_body` inside `get_body` I could just pass in the `ctx.bufferd_proxying` we've read already. 
I think we can revert the `get_raw_body` change, and inside the `get_body` function, just replace the `get_raw_body` call with `return ctx.buffered_body or ""`, because we already do the `chech_phase` and `ctx.buffered_proxying` check, what do you think?

2025-01-13 01:30 UTC, ProBrian commented on kong/pdk/service/response.lua
> +    local buffered = buffered_proxying or ctx.buffered_proxying
> I am not sure about that. Adding `buffered_proxying` as public interface parameter feels a bit wrong. Also what if someone passes `false` here?

Yes this seems a little be confused if users pass in false but we will still respect the ctx.bufferred_proxying.
My intention was to reduce the read of ctx, because local variable is faster than ctx, and when invoke get_raw_body inside get_body I could just pass in the ctx.bufferd_proxying we've read already.
I think we can revert the get_raw_body change, and inside the get_body function, just replace the get_raw_body call with return ctx.buffered_body or "", because we already do the chech_phase and ctx.buffered_proxying check, what do you think?

2025-01-13 09:06 UTC, bungle requested changes
Let's revert all the API changes and related changes in where the changed APIs were used. Benefit vs. drawbacks are too small. Those optimizations can be implemented inside plugins themselves if they are that good. In many cases it also depends whether plugins is reading single or multiple headers to what to use, eg. is. get_headers better than multiple get_header and is multiple get_header better with created context table at what count?

2025-01-13 09:06 UTC, bungle commented on kong/pdk/service/response.lua
> +    local buffered = buffered_proxying or ctx.buffered_proxying
Yes, I would revert these PDK API changes (where we add new parameters). Not worth it, and paints us in a corner.

2025-01-13 09:27 UTC, ProBrian commented on kong/pdk/request.lua
> +  function _REQUEST.get_header(name, ctx)
What if we use `kong.tools.get_header(name, ctx)` directly in plugins, to replace non-cached `kong.request.get_header` API in certain places to achieve the cache benefit? It must be better to use PDK APIs in plugins, but I do see that there are a lot of `kong.tools` usage in plugins(which I feel more like should be used "internally" in core or some non-plugin module?), Do you think it's a proper practice?

2025-01-24 02:30 UTC, ProBrian commented
> Let's revert all the API changes and related changes in where the changed APIs were used. Benefit vs. drawbacks are too small. Those optimizations can be implemented inside plugins themselves if they are that good. In many cases it also depends whether plugin is reading single or multiple headers to what to use, eg. is. get_headers better than multiple get_header and is multiple get_header better with created context table at what count?

Removed all public API changes. @bungle

2025-01-31 08:59 UTC, bungle commented on kong/pdk/request.lua
> +  function _REQUEST.get_header(name, ctx)
@ProBrian In general it would be best if we can get to state where there is no `require "module"` statements in plugins. That is we have a powerful PDK. But meanwhile, yes, many plugins require different modules. That also then spreads to all custom plugins as plugins are copy pasted. That then will make all our internal APIs and tools public too which we cannot break. I think for example those plugins, just call get_headers once and work with headers and call it done, rather than pass a table to somewhere that something else caches the get_headers.

2025-01-31 09:02 UTC, bungle commented
@ProBrian I'll setup a meeting, where we can discuss how to get this in.

2025-02-07 08:17 UTC, bungle approved these changes

2025-02-07 08:22 UTC, chronolaw commented on kong/globalpatches.lua
> +      end
Add a `-- ]`?

2025-02-07 08:23 UTC, chronolaw commented on kong/globalpatches.lua
> +        if not ngx.ctx.body_read then
`body_read` is too common to conflict, could we give it a little long name?

2025-02-07 08:26 UTC, chronolaw commented
Do we have any data about improvements?

2025-02-07 08:26 UTC, ProBrian commented on kong/globalpatches.lua
> +        if not ngx.ctx.body_read then
good point

2025-02-07 08:41 UTC, chronolaw commented on kong/plugins/grpc-web/handler.lua
> +    ngx.var.http_content_type,
```suggestion
    ngx_var.http_content_type,
```

2025-02-07 08:43 UTC, chronolaw commented on kong/plugins/oauth2/access.lua
> +      local content_type = ngx.var.http_content_type
should we add `local ngx_var = ngx.var`?

2025-02-07 08:43 UTC, chronolaw commented on kong/plugins/request-transformer/access.lua
> +local var = ngx.var
```suggestion
local ngx_var = ngx.var
```

2025-02-07 08:49 UTC, ADD-SP commented on t/01-pdk/08-response/02-get_header.t
> +=== TEST 4: response.get_header() returns existing header will not limited by get_headers() default max_headers configuration
Is this a new feature?

2025-02-07 08:55 UTC, ProBrian commented on t/01-pdk/08-response/02-get_header.t
> +=== TEST 4: response.get_header() returns existing header will not limited by get_headers() default max_headers configuration
It's not a new feature, just a refine, since we use `ngx.header[name]` to replace `_RESPONSE.get_headers()[name]` in the `get_header` implementation, the max headers limitation brought by `get_headers()` will not exist anymore.

2025-02-07 09:04 UTC, ProBrian commented on t/01-pdk/08-response/02-get_header.t
> +=== TEST 4: response.get_header() returns existing header will not limited by get_headers() default max_headers configuration
I thinks it's not needed to consider this a new feature, because 
1. the limitation is due to our internal implementation.
2. the limitation is not documented which means users aren't even aware of this limitation.
that means we have no interface changes and no documentation changes from user's perspective.

2025-02-07 09:35 UTC, chronolaw commented on kong/plugins/oauth2/access.lua
> +      local content_type = ngx.var.http_content_type
This function may be called many times, I think.

2025-02-10 10:37 UTC, chronolaw commented on kong/plugins/grpc-web/handler.lua
> +    ngx_var.http_content_type,
It may not correct, since now nginx could return multiple headers in one value, like "a, b, c".
could you check other places? thanks.

2025-02-10 10:38 UTC, chronolaw commented on kong/plugins/grpc-web/handler.lua
> +    ngx_var.http_content_type,
@bungle , could you verify it? thanks.

2025-02-10 14:48 UTC, bungle requested changes
I tested this and one assumption was not correct.

2025-02-10 14:48 UTC, bungle commented on kong/pdk/request.lua
> +    local content_type = mimetype or ngx.var.http_content_type
@ProBrian

`ngx.var.content_type` does not seem to be single header. If you send multiple, you will get `"<value1>, <value2>, ..."`.

2025-02-10 14:56 UTC, bungle commented on kong/pdk/request.lua
> +    local content_type = mimetype or ngx.var.http_content_type
What is even more annoying is that:
```
ngx.req.set_header("Content-Type", "value")
```

is not reflected with `ngx.var.http_content_type`.

2025-02-10 16:33 UTC, bungle commented on kong/pdk/request.lua
> +    local content_type = mimetype or ngx.var.http_content_type
It also looks that our Kong module plays some role here.

2025-02-10 16:38 UTC, bungle commented on kong/pdk/request.lua
> +    local content_type = mimetype or ngx.var.http_content_type
This seems to work properly:
```
local ct = kong.request.get_header("Content-Type")
ngx.req.clear_header("Content-Type")
ngx.req.set_header("Content-Type", ct)
```

If I don't do `clear_header`, it does not work properly.

2025-02-10 16:38 UTC, bungle commented on kong/pdk/request.lua
> +    local content_type = mimetype or ngx.var.http_content_type
This is the request I am using:
```
http -v :8001 Content-Type:text/html Content-Type:text/json
```

2025-02-11 07:43 UTC, ProBrian commented on kong/pdk/request.lua
> +    local content_type = mimetype or ngx.var.http_content_type
> together
Seems there's a mismatch limitation between openresty and nginx that I've ignored, that is,

- nginx allows multiple line values for headers like "Content-Type".

- And openresty defines a list of headers that is "built-in single value", which includes "Content-Type". ngx.req.set_header will not allow multiple value for "Content-Type", so if we  ngx.req.set_header("Content-Type", {"json1", "json2"}) , it will use the last elem as the single value, so then ngx.req.get_headers()["Content-Type"] and ngx.var.http_content_type will all get a single value "json2" .

- But when multiple content type header is sent by http request client, not by openresty set_header API, then the header value is just handled by nginx, and get_headers will get a table {"json1", "json2"} and `ngx.var.http_content_type  will get the value as comma separated string: "json1, json2".

2025-02-11 07:49 UTC, ProBrian commented on kong/pdk/request.lua
> +    local content_type = mimetype or ngx.var.http_content_type
> What is even more annoying is that:
> 
> ```
> ngx.req.set_header("Content-Type", "value")
> ```
> 
> is only reflected with the first value. Seems like `clear_header` is needed together with `set_header`?

That's due to the implementation of openresty, it assumes that `Content-Type` should be single value, so in set_header implementation, the assignment will only take place in the first index of value list.

2025-02-11 08:13 UTC, ProBrian commented on kong/pdk/request.lua
> +    local content_type = mimetype or ngx.var.http_content_type
I will rollback the `var.http_content_type` changes, since `kong.request.get_header` will only get the first value no matter `content-type` is multi value or not from downstream; but `var.http_content_type` rely on the assumption that downstream send single `content-type` or `content-type` is set by `ngx.req.set_header`.

2025-02-12 02:46 UTC, chronolaw commented on kong/pdk/response.lua
> +    local header_value = ngx.header[name]
Should we keep the original code here?

2025-02-12 02:46 UTC, chronolaw commented on kong/plugins/aws-lambda/request-util.lua
> +      local content_type = kong.request.get_header("Content-Type")
It seems that we should not change this line.

2025-02-12 02:46 UTC, chronolaw commented on kong/plugins/cors/handler.lua
> +  local req_origin = headers["origin"]
Could you confirm it is ok?

2025-02-12 02:46 UTC, chronolaw commented on kong/plugins/cors/handler.lua
> +  local req_origin = headers["origin"]
Could you confirm it is ok?

2025-02-12 02:46 UTC, chronolaw commented on kong/plugins/cors/handler.lua
> +     or not headers["Origin"]
Could you confirm it is ok?

2025-02-12 03:00 UTC, ProBrian commented on kong/pdk/response.lua
> +    local header_value = ngx.header[name]
`ngx.header` is the better way to get a single response header, and it returns the same type of values as `get_headers()[name]`: if `get_headers()[name]` get a table, `ngx.header` will get a table similarly(unlike `ngx.var.sent_http_` which returns comma separated string). So we make this change for better performance.

2025-02-12 06:18 UTC, ProBrian commented on kong/plugins/cors/handler.lua
> +  local req_origin = headers["origin"]
That's a tricky point, here we want to use `headers` result as param to reduce duplicated `get_header` call. Although `origin` header should not be a multiple value logically, but users may still send `http http://xxx/yyy Origin:o1 Origin:o2` from downstream which doesn't quite make sense as I see(also I feel like two `Content-Type` header in one http request is also not quite logically correct...). 
But anyway in this case `kong.request.get_header("origin")` will get only first value `o1` and `get_headers()["origin"]` will get `{o1, o2}`.
So the `get_header` API guarantees we only get a single value no matter it's multiple value or not. But in the other side, its pointless to run `get_header` multiple times since the header has not been changed. Maybe we could just change this to:
`type(headers["origin"]) == "table" and headers["origin"][1] or headers["origin"]`
which is the implementation to make header value always single(see https://github.com/Kong/kong/blob/master/kong/tools/http.lua#L564).
@bungle @chronolaw

2025-02-14 08:26 UTC, ProBrian commented on kong/pdk/service/request.lua
> +        mime = get_header(CONTENT_TYPE)
Here `get_header` guarantee `Content-Type` header's value is a string. `get_headers()[CONTENT_TYPE]` may returns a table if downstream sends multiple `Content-Type` headers.
From https://github.com/Kong/kong/pull/13981/files#diff-fab5190a31719b5022535ea42add0ef30683a4fe22ba208fd0976908e13c0d3bL664 we can see that `mime` here must be a string.

2025-02-14 08:31 UTC, ProBrian commented
I have reverted the changes which replaced `kong.request.get_header(name)` with `headers = get_headers(); headers[name]`, since `kong.request.get_header(name)` guarantees header value is a string but `get_headers()[name]` not. 
Please help to review again, @bungle  @chronolaw

2025-02-17 03:25 UTC, ProBrian commented on kong/plugins/cors/handler.lua
> +  local req_origin = headers["origin"]
Keep using `kong.request.get_header("origin")`

2025-02-17 03:25 UTC, ProBrian commented on kong/plugins/cors/handler.lua
> +  local req_origin = headers["origin"]
Keep using `kong.request.get_header("origin")`

2025-02-17 05:12 UTC, chronolaw commented on kong/pdk/request.lua
> -
I think it is a unnecessary change, right?

2025-02-18 01:46 UTC, ProBrian commented on kong/pdk/request.lua
> -
reverted

2025-02-21 08:01 UTC, chronolaw approved these changes

2025-02-28 12:07 UTC, bungle approved these changes

2025-03-03 02:02 UTC, ADD-SP approved these changes

2025-03-03 02:04 UTC, merged