fix(certificates):fix missing info when fields was absent
Kong/kong pull request #14032
Opened 2024-12-18 04:01 UTC by lhanjian

### Summary

### Checklist

- [ ] The Pull Request has tests
- [ ] A changelog file has been created under `changelog/unreleased/kong` or `skip-changelog` label added on PR if changelog is unnecessary. [README.md](https://github.com/Kong/gateway-changelog/blob/main/README.md)
- [ ] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

### Issue reference

Fix FTI-6351

2024-12-18 04:08 UTC, outsinre approved these changes, later dismissed

2024-12-18 06:10 UTC, lhanjian commented on spec/02-integration/04-admin_api/15-off_spec.lua
> +  it("flatten_errors1 when conflicting inputs", function()
Only add a test, not about `errors.lua` change

2024-12-19 15:09 UTC, chobits requested changes

2024-12-19 15:09 UTC, chobits commented on kong/db/errors.lua
> +          field_err_t = entity_type..":"..field_err_t..":"..ref.field
```suggestion
          field_err_t = entity_type .. ":" .. field_err_t .. ":" .. ref.field
```

2024-12-20 06:26 UTC, chobits approved these changes, later dismissed

2024-12-20 17:06 UTC, flrgh reviewed
Please do not merge yet. I have some changes to suggest but have not had time to fully review.

2025-01-08 06:59 UTC, lhanjian commented
@flrgh hi, do you have more comments?

2025-01-11 00:10 UTC, flrgh commented
I don't think this change is needed. I don't see the error string change (`entity_type..":"..field_err_t..":"..ref.field`) as particularly helpful in the general sense, and (more importantly) the error that is being used as a test case in this changeset is caused by a bug that will be fixed by #14082, so it will actually be unreachable once that PR is merged.

2025-01-14 02:24 UTC, lhanjian commented
> Sorry for blocking this for such a long while. Now that I am caught up on the context, I don't think this is needed. I don't see the error string change (`entity_type..":"..field_err_t..":"..ref.field`) as particularly helpful in the general sense, and--more importantly--the error that is being used as a test case in this changeset is caused by a bug that will be fixed by #14082, so it will actually be unreachable once that PR is merged.

ok, wait for #14082 merged, and i will recheck this pr if necessary.

2025-01-14 02:31 UTC, chronolaw commented on kong/db/errors.lua
> +          field_err_t = entity_type..":"..field_err_t..":"..ref.field
We should fix style issue.

2025-02-20 09:15 UTC, lhanjian commented on kong/db/errors.lua
> +        if type(field_value) == "table" and kong_table.is_array(field_value) then
@flrgh 
 
i think found the real problem of this situation, can you take a look?


cc @windmgc

2026-03-30 08:18 UTC, closed without merging