feat(oauth2) add ability to persist refresh tokens
Kong/kong pull request #5264
Opened 2019-11-26 20:23 UTC by amberheilman

### Summary
Add support for persisting oauth2 refresh tokens. Follows guidelines in [RFC6749](https://tools.ietf.org/html/rfc6749#section-6) to allow for the optional persistence of the refresh token when refreshing an access token.

### Related discussion
https://discuss.konghq.com/t/long-lived-refresh-tokens/659
https://discuss.konghq.com/t/long-lived-oauth-2-refresh-tokens/3005

2019-11-26 20:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=5264) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=5264) before we can accept your contribution.<br/><hr/>**amberh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=5264) it.</sub>

2019-11-26 23:41 UTC, bob983 commented
This is a nice coincidence, we started chatting about similar issue here https://github.com/Kong/kong/issues/5252.

2019-11-28 16:00 UTC, dave-shawley commented
@bob983 - we ran into the disappearing token problem using another company's OAuth 2 API and decided that we simply couldn't put our customers through the same pain.  Hopefully this will meet your needs as well.  We briefly looked into supporting multiple linked tokens side-by-side instead of making them persistent and it was quite a bit more work than expected.  Ultimately, making refresh tokens immutable until revocation met our needs.

We did implement [RFC-7009 token revocation] as a separate service using the `DELETE /oauth2_tokens/:token_id` Admin API endpoint.  That handled the need to explicitly revoke either an access token or a refresh token mentioned in #5652 .  We could look into contributing that back if there is interest.

[RFC-7009 token revocation]: https://tools.ietf.org/html/rfc7009

2019-11-28 16:14 UTC, bob983 commented
@dave-shawley yeah, this would definitely work for us well :) 

We handle the token revocation via our own UI which in turn calls the Kong Admin API and deletes the refresh token / acess token pair and thus RFC-7009 is not necessary for us but it would be a nice addition.

2020-02-11 13:23 UTC, bob983 commented
Any news on this PR? I'm eagerly watching it :)

2020-02-12 19:02 UTC, bungle requested changes
This is bit off-topic, but mind you change these as well, perhaps another commit:
refactor(oauth2) change generate_token parameters

2020-02-12 19:17 UTC, bungle commented
In general I think this is good... only thing I am hesitating is the quite long and perhaps a bit misleading (as all the refresh tokens are persistent, but not reusable currently):
```
persistent_refresh_token
```

We already have:
```
config.refresh_token_ttl
```

@dave-shawley, what do you think e.g.:_
```
config.refresh_token_reuse=true
```
or
```
config.refresh_token_reusable=true
```
or
```
config.reuse_refresh_token=true
```

Pick what you like the best. I think after that we can go ahead and merge. Please also rebase to latest `next` and change the PR to be merged to `next` as that is where `feats` go.

Thank you for the PR. I have to say that these are very high in quality. We should have reviewed this earlier. I'll focus to get these in!

2020-02-15 19:03 UTC, amberheilman commented
@bungle,
PR has been rebased against next. 
Changed the configuration option from `persistent_refresh_token` to `reuse_refresh_token` as well.

2020-02-17 13:52 UTC, bungle approved these changes

2020-02-17 13:53 UTC, merged

2020-02-17 13:53 UTC, bungle commented
@amberheilman, thank you sir! it is finally merged now, and will land on `2.1`.