feat/plugins-rate-limiting by path.
Kong/kong pull request #6234
Opened 2020-08-15 00:23 UTC by fairyqb

**Summary**

add plugins-rate-limiting limit by path.

2020-08-19 14:22 UTC, bungle commented
Can you please rebase this on `next branch` as new `features` goes to `next` branch, thank you.

2020-08-21 06:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=6234) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=6234) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: taotao2014<br/>:x: KongGuide<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=6234) it.</sub>

2020-08-21 07:16 UTC, fairyqb commented
OK, #6263

2020-08-28 00:51 UTC, fairyqb commented
> Can you please rebase this on `next branch` as new `features` goes to `next` branch, thank you.

@bungle  @Tieske 
sorry, rebase completed now

2020-09-02 09:41 UTC, dndx requested changes

2020-09-02 09:41 UTC, dndx commented on kong/plugins/rate-limiting/schema.lua
> +          { path = typedefs.path },
The above code does not make use of this config at all and should probably be removed.

2020-09-02 09:41 UTC, dndx commented on kong/plugins/rate-limiting/handler.lua
> +    identifier = kong.request.get_path(conf.path)
`kong.request.get_path` does not expect any arguments, so `conf.path` is not used at all here.

2020-09-02 17:23 UTC, kikito commented
Merged with fixes in #6286. Thanks!

2020-09-02 17:23 UTC, closed without merging