pdk.kong.request.cookie
Kong/kong pull request #6262
Opened 2020-08-21 06:23 UTC by fairyqb

Summary

add kong.request.cookie

2020-08-21 06:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=6262) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=6262) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=6262) it.</sub>

2020-08-24 03:48 UTC, fairyqb commented
request to merge ? @Tieske  @bungle

2020-08-24 05:21 UTC, Tieske commented
@fairyqb I did leave some comments, which haven't been resolved yet.

2020-08-24 06:35 UTC, Tieske requested changes
minor typo

2020-08-24 06:35 UTC, Tieske commented on kong/pdk/request.lua
> +  -- Values are either a string with the cookie value.
```suggestion
  -- Values are strings with the cookie value.
```

2020-08-24 08:05 UTC, fairyqb commented
@Tieske , finished, thank you.

2020-08-24 15:21 UTC, Tieske requested changes
sorry, 2 more minor typo things

2020-08-24 15:21 UTC, Tieske commented on kong/pdk/request.lua
> +  -- Cookie names in are case-sensitive.
```suggestion
  -- Cookie names are case-sensitive.
```

2020-08-24 15:21 UTC, Tieske commented on kong/pdk/request.lua
> +  ---
two lines with `---`

2020-08-24 15:22 UTC, Tieske commented
@bungle would you mind also having a look at this one? (also; shouldn't this be targetted on `next` instead of `master`)

2020-08-24 15:47 UTC, fairyqb commented on kong/pdk/request.lua
> +  ---
ok.

2020-08-24 16:08 UTC, fairyqb commented on kong/pdk/request.lua
> +  -- Cookie names in are case-sensitive.
thank you.

2020-08-24 16:09 UTC, fairyqb commented
> @bungle would you mind also having a look at this one? (also; shouldn't this be targetted on `next` instead of `master`)

#6273

2020-08-24 17:23 UTC, Tieske commented
@fairyqb no need to send a second pr, you can rebase your branch on the next branch and force push, then in the github ui edit the pr (button at top right) and change the target branch

2020-08-25 06:23 UTC, fairyqb commented
I got it

2020-08-25 06:23 UTC, closed without merging