refactored readme
Kong/kong pull request #6283
Opened 2020-08-28 20:04 UTC by iamrajiv

### Summary

Fixed grammatical mistakes and formatted README.md

2020-08-28 20:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=6283) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=6283) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=6283) it.</sub>

2020-09-10 19:39 UTC, iamrajiv commented
@guanlan Please review.

2020-09-11 20:40 UTC, iamrajiv commented
@javierguerragiraldez @locao Please review.

2020-09-11 20:41 UTC, iamrajiv commented
@hutchic Is it ready to be merged?

2020-09-11 20:56 UTC, javierguerragiraldez requested changes

2020-09-11 20:56 UTC, javierguerragiraldez commented on README.md
>    critical use cases and high throughput.
i think this "the" isn't appropriate here.

2020-09-11 20:56 UTC, javierguerragiraldez commented on README.md
> +- **Hash-based Load Balancing**: Load balance with consistent hashing/sticky sessions.
this only removes wrapping in the sources, no effect on the result.

2020-09-11 20:56 UTC, javierguerragiraldez commented on README.md
> +  using the Azure Resource Manager.
i think "the" isn't appropriate here.  how is it on microsoft docs?

2020-09-11 20:56 UTC, javierguerragiraldez commented on README.md
> +  Instaclustr manages your Cassandra cluster.
typo?

2020-09-11 20:56 UTC, javierguerragiraldez commented on README.md
> +If you are planning on developing in Kong, you'll need a development
personally, i use "developing in" a language, but "developing on" a platform.  not sure if there's any grammar rule relevant.

2020-09-11 20:56 UTC, javierguerragiraldez commented on README.md
> +You can read more about writing your plugins in the [Plugin Development
i feel that "your plugins" makes sense if they've been mentioned before.  the first time "your own plugins" sounds better.

2020-09-11 20:56 UTC, javierguerragiraldez commented on README.md
> +- Plugins tests, which require Postgres to be running
AFAICT, most markup engines treat '*' and '-' as equivalent when defining lists.

2020-09-11 20:56 UTC, javierguerragiraldez commented on README.md
> +|         `test-all` | Run all unit + integration + plugins tests at once |
not sure if it has any effect or not.  if not, it only makes it harder to maintain.

2020-09-11 21:08 UTC, iamrajiv commented
@javierguerragiraldez Take a look now. I have formatted the README using Prettier and Grammarly.

2020-09-21 11:30 UTC, iamrajiv commented
@javierguerragiraldez Take a look now. I have formatted the README using Prettier and Grammarly.

2020-10-02 02:09 UTC, closed without merging