test(plugins) Add buffering combinations iterator
Kong/kong pull request #6431
Opened 2020-10-04 22:34 UTC by javierguerragiraldez

Because we all want to spend 4x times on tests...

2020-10-08 18:06 UTC, kikito approved these changes
This looks ok to me (assuming the tests pass).

Note for other reviewers: I strongly suggest reviewing this pr with the cog menu (⚙️▾) and then "✅Hide whitespace changes" option. Makes all the difference.

2020-10-09 07:23 UTC, Tieske requested changes
these are 2 additional layers of permutations for testing, can we not replace them with a single layer by using dynamic permutations?

for example;
```lua
local permute_bool = { true, false }

for strategy, buf_req, buf_res in permute({helpers.strategies, permute_bool, permute_bool }) do

  -- test stuff

end
```

2020-10-09 07:23 UTC, Tieske commented on spec/helpers.lua
> +local each_buffering
documentation is missing here

2020-10-09 12:09 UTC, Tieske commented
I thought Penlight had a function for this, turned out not; https://github.com/lunarmodules/Penlight/pull/360

2020-10-21 13:56 UTC, Tieske commented
@javierguerragiraldez how to proceed? I can push a Penlight version with the permutations iterator if you want.

2020-10-21 14:02 UTC, javierguerragiraldez commented
> @javierguerragiraldez how to proceed? I can push a Penlight version with the permutations iterator if you want.

Thanks, no need to.  this PR won't be merged.  it's more an experiment to test that the new buffering cases don't crash anything catastrophically.

i'm closing this, as it has already proved the point.

2020-10-21 14:02 UTC, closed without merging