docs(readme) mention the non-root way of running kong
Kong/kong pull request #6595
Opened 2020-11-20 13:48 UTC by murillopaula

Copy and pasted the description from the EE changelog https://docs.konghq.com/enterprise/changelog/#core

2020-11-24 11:01 UTC, kikito approved these changes

2020-12-02 18:12 UTC, kikito requested changes
Feedback from user in https://github.com/Kong/kong/issues/6591#issuecomment-732903514: 

> I'd call it out a bit more explicitly that ownership of directories has changed from nobody to kong and that if your config currently has nginx user set to nobody you must update it to be kong

> The way it's worded at the moment doesn't really make it sound like it'd break existing configs.

> The default config needs updating too.

2020-12-10 15:10 UTC, murillopaula commented
@kikito IMHO we should still merge this as it is now. We forgot to include it in the 2.2.0 changelog.

I believe that In 2.2.2 we'll include the fix for the issue #6591 (see the PR #6421). So I'm not sure if it's needed to say in the 2.2.0 changelog there is a bug that was fixed in 2.2.2... 🤔

2020-12-10 15:22 UTC, kikito approved these changes

2020-12-10 15:22 UTC, merged