fix(conf) combine trusted certs in conf_loader
Kong/kong pull request #6650
Opened 2020-12-11 20:34 UTC by murillopaula

The commit 1e6afa171272a12a1577c7f7e172a5a0cac4ca30 introduced a regression for a case where we want to enable verification of database certificates when doing SSL handshake connections. For example, if we wanted to specify `pg_ssl = on` and `pg_ssl_verify = on` to enable verification of the postgres certificate, the following error would be thrown:

```
Error:
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:220: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: error loading CA locations (No such file or directory)
stack traceback:
[C]: in function 'assert'
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:220: in function 'cmd_exec'
/usr/local/share/lua/5.1/kong/cmd/init.lua:96: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:96>
[C]: in function 'xpcall'
/usr/local/share/lua/5.1/kong/cmd/init.lua:96: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:53>
/usr/local/bin/kong:9: in function 'file_gen'
init_worker_by_lua:48: in function <init_worker_by_lua:46>
[C]: in function 'xpcall'
init_worker_by_lua:55: in function <init_worker_by_lua:53>
```

The aforementioned commit added support for configuring a list of `lua_ssl_trusted_certificate` and the paths on the list are concatenated into a single file in a fixed location (`$PREFIX/.ca_combined`). The configuration used for enabling verification of database certificates was defined by the new `lua_ssl_trusted_certificate_combined` property.

But the problem was that the generation of the combined file containing the trusted certificates was done in the `prefix_handler` module. Commands such as `kong migrations bootstrap` would fail because they don't use the `prefix_handler` module. The correct place should be in `conf_loader` where the `lua_ssl_trusted_certificate_combined` is first defined.

2020-12-28 16:49 UTC, dndx approved these changes

2020-12-28 16:56 UTC, dndx requested changes
Actually, one thing I just noticed:

Because the migrations helper does not run the prefix handler, that means the prefix directory may not be created yet, and then the `migration` command could fail with the following error:

```
$ KONG_LUA_SSL_TRUSTED_CERTIFICATE=spec/fixtures/kong_clustering.crt,spec/fixtures/kong_clustering_ca.crt ./bin/kong migrations bootstrap -v
2020/12/28 08:54:19 [verbose] Kong: 2.2.1
2020/12/28 08:54:19 [verbose] no config file found at /etc/kong/kong.conf
2020/12/28 08:54:19 [verbose] no config file found at /etc/kong.conf
2020/12/28 08:54:19 [verbose] no config file, skip loading
2020/12/28 08:54:19 [verbose] generating trusted certs combined file in 
Error: 
./kong/conf_loader/init.lua:1180: /usr/local/kong/.ca_combined: No such file or directory
stack traceback:
	[C]: in function 'assert'
	./kong/conf_loader/init.lua:1180: in function 'gen_trusted_certs_combined_file'
	./kong/conf_loader/init.lua:1584: in function 'conf_loader'
	./kong/cmd/migrations.lua:82: in function 'cmd_exec'
	./kong/cmd/init.lua:88: in function <./kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	./kong/cmd/init.lua:88: in function <./kong/cmd/init.lua:45>
	./bin/kong:9: in function 'file_gen'
	init_worker_by_lua:48: in function <init_worker_by_lua:46>
	[C]: in function 'xpcall'
	init_worker_by_lua:55: in function <init_worker_by_lua:53>
```

I wonder instead of moving the location, we should instead call the prefix handler for `migrations` command as well. `conf_loader` should really not be writing files to the filesystem for the reason above.

Or maybe we should use a temporary file just for migrations instead? I don't see the obvious benefit of doing this than just use the prefix handler.

Ping @kikito as well.

2021-01-04 18:43 UTC, murillopaula commented
Hello @dndx and @kikito,

> I wonder instead of moving the location, we should instead call the prefix handler for migrations command as well. conf_loader should really not be writing files to the filesystem for the reason above.

Ok, so if I understood correctly, the proposed change is to not move the location but instead call the `prepare_prefix` function that's inside the `prefix_handler` module in the following places:

1) migrations `up`: https://github.com/Kong/kong/blob/master/kong/cmd/utils/migrations.lua#L57-L123
2) migrations `bootstrap`: https://github.com/Kong/kong/blob/master/kong/cmd/utils/migrations.lua#L25-L54
3) migrations `finish` ???
4) migrations `reset` ???
5) migrations `check_state` ???

1 and 2 for sure would need to call `prefix_handler`, what about the other three?


> Because the migrations helper does not run the prefix handler, that means the prefix directory may not be created yet, and then the `migration` command could fail with the following error:
>
> ...

But actually, before we commit any efforts into this, would you mind elaborating more about the problem? I'd like to understand why this happens and how I can reproduce this. Did you try with my branch `fix/combined-certs`? My prefix has not been created yet, and then the `kong migrations bootstrap` command succeeds

Thanks

2021-01-05 17:46 UTC, dndx commented
@murillopaula Because we have this logic https://github.com/Kong/kong/blob/master/kong/cmd/utils/prefix_handler.lua#L260-L267 that checks the prefix directory and creates it if needed in the `prefiix_handler`, that's why I think using it is a better idea.

Another reason is that we want to avoid writing the filesystem in the conf loader if we could. A lot of things depends on it and sometimes the user only want to check a config to be valid, but we are generating a side effect (writing a file in the disk).

If we call `prefix_handler` for all `migration` commands that should be okay. This way at least the side effects are still obvious to the user and all contained under a single directory.

2021-01-05 23:58 UTC, murillopaula commented
@dndx in this case then if we don't want to move the function to `conf_loader` we'll have to call `prefix_handler` in the `start.lua` module as well. If not, we'll keep getting the error:

```
2021/01/05 23:23:32 [verbose] prefix in use: /kong_prefix
Error: 
/kong/kong/cmd/start.lua:31: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: error loading CA locations (No such file or directory)
stack traceback:
        [C]: in function 'assert'
        /kong/kong/cmd/start.lua:31: in function 'execute'
        /kong/kong/cmd/restart.lua:33: in function 'cmd_exec'
        /kong/kong/cmd/init.lua:88: in function </kong/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /kong/kong/cmd/init.lua:88: in function </kong/kong/cmd/init.lua:45>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:47: in function <init_worker_by_lua:45>
        [C]: in function 'xpcall'
        init_worker_by_lua:54: in function <init_worker_by_lua:52>
```

If you look at the stack trace, this is where things start to break: https://github.com/Kong/kong/blob/master/kong/cmd/start.lua#L31

It tries to initiate a connection to the DB, but we can't do that yet because our Postgres DB is using SSL, we have enabled SSL verification with `pg_ssl_verify` and therefore we would need to call `prefix_handler` at some point before the execution gets in that line in order for us to generate the `lua_ssl_trusted_certificate_combined` configuration with the list of all CAs.

Addressed it in my amended commit that I've just force-pushed (commit message updated as well).

2021-01-06 13:43 UTC, dndx approved these changes

2021-01-06 14:15 UTC, dndx approved these changes

2021-01-06 14:15 UTC, merged