fix(balancer) use a FIFO for eventual consistency updates
Kong/kong pull request #6833
Opened 2021-02-11 19:50 UTC by locao

When using eventual worker consistency, instead of trying to synchronize
all workers using a shared dictionary, share the events, and let each
worker deal with its updates.

This PR also fixes several IPv6 issues in balancer tests.

2021-02-15 09:45 UTC, bungle commented on kong/runloop/balancer.lua
> +    return
I know this is not about this PR, but I have one question about this.

With `eventual` when it was first introduced for `router` and `plugin iterator` rebuilds, it meant `only eventual`. That also meant that it was `always on`. Things were prepared in a background. `strict` meant that on request time we do check if those are up to date, that check we don't do with `eventual`, thus the `only eventual`.

I am not sure does the balancer take same approach, but I think it should if it is possible.

2021-02-18 19:11 UTC, murillopaula requested changes
I think most of my comments fall into the bigger bucket of the following problems:

1) High DB queries when sending a request to Admin API upstream endpoints;
2) A large number of `SELECT * FROM upstreams` queries are issued to the DB during kong restart, causing a high load on the DB

Problem 1) is more systematic, it is present in the router and plugin iterator as well. But I think we should take this opportunity to solve it here in the balancer in this PR by trying to address my comments.

Problem 2) is present with and without this PR, unfortunately. Right now for both strict and eventual, we create all balancers by loading all upstreams from the DB into memory on a timer, in the background, right after the init_worker phase finishes. A large number of queries are issued to DB, causing a high load on the DB after kong starts. Can we optimize it in this PR as well? I'd suggest we try to not load all upstreams from DB into memory in the `init()` function here in this PR, this way we can improve the situation at least for the `eventual` consistency. Then we can go back to the `strict` once we're done with `eventual`.

2021-03-03 16:01 UTC, locao commented on kong/runloop/balancer.lua
> +    upstream_by_name[by_name_key] = nil
I agree with the order suggested and that we should do that, but let's do this change next.

2021-03-03 16:01 UTC, locao commented on kong/runloop/balancer.lua
> +      singletons.core_cache:invalidate_local(upstream_cache_key)
Fixed, thanks!

2021-03-03 16:04 UTC, locao commented on kong/runloop/balancer.lua
>    end
Done, thanks!

2021-03-03 17:19 UTC, kikito approved these changes
This change looks good to me, I have gone over it with @locao . I would appreciate a ✅ from @murillopaula before the merge since he's more involved than me on this part of the code.

2021-03-03 18:10 UTC, murillopaula approved these changes
LGTM, reviewed IRL about it!

2021-03-03 20:16 UTC, merged