fix(utils) accept hosts ending in dots
Kong/kong pull request #6864
Opened 2021-02-24 15:12 UTC by locao

According to [RFC 3986 - section 3.2.2](https://tools.ietf.org/html/rfc3986#section-3.2.2) hosts can end in dots

Kong/lua-resty-dns-client#120 is a sister PR and this one should not be merged before the `lua-resty-dns-client` release with that fix included.

2021-02-24 15:38 UTC, kikito approved these changes
Approved with minor typo notice

2021-02-24 15:38 UTC, kikito commented on kong/tools/utils.lua
> +  --   - punycode allowes prefixed dash, if the characters before the dash are escaped
Let's fix the typos while we're here
```suggestion
  --   - punycode allows prefixed dash, if the characters before the dash are escaped
```

2021-03-04 17:25 UTC, gszr requested changes
Should this PR target `next` instead, as we do not usually do library bumps in master?

2021-03-12 19:15 UTC, Tieske commented
imo, the lib only had a bugfix, so `master` should be fine as well, no?

2021-03-16 14:56 UTC, merged