perf(*) collective perf branch 2.6
Kong/kong pull request #7840
Opened 2021-09-13 13:21 UTC by fffonion

All perf related PR goes to here so we can compare with master.

2021-09-14 14:50 UTC, kikito approved these changes

2021-09-14 15:19 UTC, bungle commented
Let's not merge just yet.

2021-09-14 15:20 UTC, bungle requested changes
Just wanting to see if this has any effect:
https://github.com/Kong/kong/pull/7849

2021-09-15 13:59 UTC, bungle approved these changes

2021-09-15 14:22 UTC, merged