feat(*) add support for exit_worker_by_lua
Kong/kong pull request #8490
Opened 2022-03-02 20:57 UTC by bungle

### Summary

Adds support for an OpenResty phase `exit_worker` in Kong core, and enables that phase for plugins too.

2022-03-09 07:11 UTC, guanlan commented on CHANGELOG.md
> +## [2.9.0] (UNRELEASED)
3.0 will be the next non-patch release

2022-03-09 07:49 UTC, chronolaw commented
Shall we modify `pdk.private.phases.lua`, add a new constant `exit_worker`?

2022-03-16 12:14 UTC, kikito requested changes
I think this requires at least one test. I think the easiest way to test this would be a custom plugin which includes the new functionality.

2022-11-02 08:52 UTC, kikito commented
@bungle can you rebase this over master please?

2022-11-02 09:09 UTC, StarlightIbuki commented
Guess we should also support it for plugin servers?

2023-02-28 10:18 UTC, closed without merging

2023-02-28 10:38 UTC, hanshuebner commented
For the benefit of everybody outside of the Kong core team, here's a bit of explanation:  The `exit_worker` phase of nginx happens when it has already closed all connections, stopped processing timers and handling its internal event loop.  This means that then environment in which `exit_worker` callbacks would execute would be very limited and much different from the normal execution environment provided to plugins.  As we are working on changes to plugins to provide a more useful way to hook into the orderly shutdown process and we also have no clear usecase for `exit_worker`, we have decided not to pursue this PR further.