tests(plugins/zipkin) make `host` and `port` of `Zipkin` configurable
Kong/kong pull request #8626
Opened 2022-04-02 03:56 UTC by ADD-SP

### Summary

Now, the `host` and `port` for `Zipkin` are fixed in the code, which is not conducive to developers running tests locally. These two parameters should be allowed to be changed via environment variables.

This PR introduces two environment variables to improve it:

* `KONG_SPEC_TEST_ZIPKIN_HOST`
* `KONG_SPEC_TEST_ZIPKIN_PORT`

2022-04-20 06:03 UTC, Suika-Kong approved these changes

2022-04-20 06:04 UTC, Suika-Kong commented on spec/helpers.lua
> +local ZIPKIN_PORT = tonumber(os.getenv("KONG_SPEC_TEST_ZIPKIN_PORT") or 9411)
not really important but

```suggestion
local ZIPKIN_PORT = tonumber(os.getenv("KONG_SPEC_TEST_ZIPKIN_PORT")) or 9411
```

2022-04-20 09:34 UTC, Tieske commented
just see they are the same as the Redis ones, so that should be fine.

2022-04-20 09:41 UTC, Tieske requested changes
the documenta comments need to be updated as well; https://github.com/Kong/kong/blob/30af56b548bf1bee6a8c493025b5498291de4afc/spec/helpers.lua#L2784

2022-04-20 10:00 UTC, Tieske commented on spec/helpers.lua
> +-- @field redis_ssl_sni The server name for Redis
good to add the Redis ones, but the Zipkin ones are still missing?

2022-05-13 14:55 UTC, Tieske commented on spec/helpers.lua
> +-- @field redis_ssl_port The port (SSL enabled) for Redis, it can be set by env KONG_SPEC_TEST_REDIKONG_SPEC_TEST_REDIS_SSL_PORTS_PORT.
this is a typo. Can you fix?

2022-05-16 16:46 UTC, merged