fix(http-log) url query parameter missing
Kong/kong pull request #8627
Opened 2022-04-02 07:38 UTC by VicYP

This commit https://github.com/Kong/kong/commit/2a608480d3f193b87a784666d99efbadb15be1aa is used to fix http log url query parameter missing issue.

2022-04-02 07:41 UTC, fffonion approved these changes

2022-04-04 07:47 UTC, bungle commented
@VicYP, is it possible to add a test case for this? Should be quite straightforward, if I understood correctly?

2022-04-06 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=8627) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=8627) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ADD-SP<br/>:x: VicYP<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=8627) it.</sub>

2022-04-06 12:22 UTC, dndx requested changes

2022-04-06 12:22 UTC, dndx commented on CHANGELOG.md
> +[#8627](https://github.com/Kong/kong/pull/8627)
```suggestion
- **http-log**: Include the query parameter when making logging requests to `config.http_endpoint`.
[#8627](https://github.com/Kong/kong/pull/8627)
```

2022-04-06 12:22 UTC, dndx commented on spec/03-plugins/03-http-log/01-log_spec.lua
> +        path = "/status/200?test0=test0&test1=test1",
This is not testing this change correctly. We need to add a plugin config like ones in https://github.com/Kong/kong/pull/8627/files#diff-50dcfdce82665f85d2027363af6956fc788e5b8f6c6b8de907e9bd82e8871501R202 and add the query parameter in the `config.http_endpoint` and make sure it works.

2022-04-06 14:40 UTC, kikito commented
I was slightly concerned about whether this is a breaking change or a bug fix, so I went out and checked [rfc1738](https://datatracker.ietf.org/doc/html/rfc1738#section-3.3), to confirm that query params are indeed considered part of the definition of a URL. So this is a bugfix, if someone is relying on query params being ignored it is ok for us to "break" things for them.

2022-04-07 09:21 UTC, dndx commented
@kikito This is less concerning to me, even in the rare case user relied on query parameters being ignored, having unneeded query parameters should not affect anything anyway as long as they are unused.

2022-09-22 08:07 UTC, samugi commented on kong/plugins/http-log/handler.lua
> +    url = url .. "? ".. parsed_url.query
I think the space after the question mark was meant to be outside of the quotes:
```suggestion
    url = url .. "?" .. parsed_url.query
```

2022-10-25 22:23 UTC, hbagdi commented
@VicYP Can you please drive this to completion?

2023-03-20 22:53 UTC, hbagdi commented
ping @VicYP

2023-03-28 19:38 UTC, hbagdi commented
ping @VicYP

2023-04-06 21:30 UTC, hbagdi commented
Closing because of lack of activity. We would like to accept this contribution if anyone wishes to pick this back up.

2023-04-06 21:30 UTC, closed without merging