test(packaging): do a quick validation that Kong can viably be packaged
Kong/kong pull request #8707
Opened 2022-04-20 22:17 UTC by hutchic

Some recent PR's have broken our ability to package / run Kong.

This PR uses our packaging / release tooling to do a single test run.

2022-04-21 11:36 UTC, kikito approved these changes

2022-04-21 13:26 UTC, hutchic commented
@kikito whoops I meant to add a `when` stanza to run this on PR after I validated by running it against this branch :laughing: 

I'll add the `when` back in as well as investigate why jenkins isn't reporting that it passed back onto this PR :thinking:

2022-04-21 15:26 UTC, kikito requested changes
Alright, changing this to "Request Changes" then so no one merges by mistake.

2022-04-25 19:15 UTC, kikito approved these changes

2022-04-25 19:58 UTC, merged