FT-2563 - FT-2563-no-daos-hash
Kong/kong pull request #8988
Opened 2022-06-22 05:12 UTC by hanshuebner

### Summary

Older Kong version accepted hash-like tables for DAO definitions.  This is no longer supported, and with this change, a clear error message is produced if a plugin returns a non-array-like table for its DAO definitions.

2022-06-22 05:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=8988) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=8988) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=8988) it.</sub>

2022-06-23 23:22 UTC, kikito approved these changes

2022-06-23 23:26 UTC, kikito requested changes

2022-06-23 23:26 UTC, kikito commented on spec/01-unit/01-db/01-schema/11-declarative_config/01-validate_spec.lua
> +       assert(not declarative_config.load(plugins_set))
A simple `assert` is ok for testing the happy path, but we should also test that the error we introduced is the one actually being returned.

```suggestion
       local ok, err = declarative_config.load(plugins_set)
       assert.falsy(ok)
       assert(<something about err>)
```

2022-06-27 08:01 UTC, bungle approved these changes

2022-06-27 08:03 UTC, merged