Update migrations.lua
Kong/kong pull request #9010
Opened 2022-06-24 19:26 UTC by cloudjumpercat

Updated `reset` command description.

### Summary

This change was requested in [DOCU-1474](https://konghq.atlassian.net/browse/DOCU-1474) because it was unclear to customers that the `reset` command would erase data instead of reset the migration steps.

### Full changelog

* Edited the description of the `reset` command

### Issue reference

Fix [DOCU-1474](https://konghq.atlassian.net/browse/DOCU-1474)

2022-06-24 19:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=9010) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=9010) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=9010) it.</sub>

2022-06-25 00:26 UTC, mayocream commented on kong/cmd/migrations.lua
> +  reset                             Reset the database. This erases Kong data and doesn't reset migration steps.
The `reset` command will erase all the data in Kong's database, and delete all the schemas.

2022-06-27 13:31 UTC, mayocream approved these changes

2022-06-27 13:56 UTC, Guaris requested changes
small nitpick

2022-06-27 14:14 UTC, Guaris approved these changes

2022-06-28 03:43 UTC, merged