docs(helpers) add docs for function `wait_timer`
Kong/kong pull request #9130
Opened 2022-07-21 09:43 UTC by ADD-SP

2022-07-21 10:24 UTC, Tieske requested changes
This doesn't even show up in the documentation? Can you try and run `ldoc` and verify?

2022-07-21 10:25 UTC, Tieske commented on spec/helpers.lua
> +---@usage helpers.wait_timer("rate-limiting", true, "all-finish", 10)
```suggestion
--- Wait for some timers, throws an error on timeout.
-- ?? what does it do? describe the "mode" parameter
-- @function wait_timer
-- @tparam string timer_name_pattern the call will apply to all timers matching
-- this string
-- @tparam boolean plain if truthy, the `timer_name_pattern` will be matched
-- plain, so without pattern matching
-- @tparam string mode one of: "all-finish", "all-running", "any-finish",
-- "any-running", or "worker-wide-all-finish"
-- @tparam[opt=2] number timeout maximum time to wait
-- @tparam[opt] number admin_client_timeout to override the default timeout setting
-- @tparam[opt] number forced_admin_port to override the default port of admin API
-- @return ????
-- @usage helpers.wait_timer("rate-limiting", true, "all-finish", 10)
```

This should work, but is incomplete. Can you check the `@return` tag and the description?

2022-07-21 10:29 UTC, ADD-SP commented
> This doesn't even show up in the documentation? Can you try and run `ldoc` and verify?

<img width="1145" alt="截屏2022-07-21 18 29 02" src="https://user-images.githubusercontent.com/44437200/180192918-cdf73fbc-2f92-45b4-aba1-4871d28fb4ec.png">

2022-07-21 11:13 UTC, Tieske commented
@ADD-SP yep,, my bad, it did show up. But is has the wrong annotations; '?' and '|' characters that are not recognized. My suggestion above takes care of that.

2022-07-22 11:26 UTC, Tieske requested changes

2022-07-22 11:26 UTC, Tieske commented on spec/helpers.lua
> +---@usage helpers.wait_timer("rate-limiting", true, "all-finish", 10)
can we please make this consistent with the rest of the file? triple-dash + space on the first line, double-dash + space on the following lines

2022-07-26 07:27 UTC, Tieske approved these changes

2022-07-27 11:35 UTC, merged