fix(request-transformer) an empty JSON array after being decoded, can…
Kong/kong pull request #9186
Opened 2022-08-03 08:03 UTC by catbro666

…'t be properly re-encoded as an array. Instead, it becomes an empty json object.

This is sister PR to PR:

[#4901](https://github.com/Kong/kong/pull/4901)

It contains a similar fix, but now to `request-transformer` (this plugin).

2022-08-03 08:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=9186) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=9186) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=9186) it.</sub>

2022-08-05 01:37 UTC, ms2008 approved these changes
LGTM

2022-08-11 08:52 UTC, chronolaw approved these changes

2022-08-11 18:15 UTC, flrgh requested changes

2022-08-11 18:15 UTC, flrgh commented on kong/plugins/request-transformer/access.lua
> +local cjson = require("cjson.safe").new()
If you're going to switch from `cjson` to `cjson.safe` then you need to update the `parse_json` local function below, as it uses `pcall`.

2022-08-16 08:19 UTC, ms2008 requested changes
https://github.com/Kong/kong/blob/a9e58a1f3c8bd2b89b1a7be67c9179d15bd06147/kong/plugins/request-transformer/access.lua#L22

This line also needs to be removed.

2022-08-16 20:25 UTC, flrgh approved these changes
:+1: lgtm; good to go after removing the now-unused `local pcall` as per @ms2008's comment.

2022-08-19 03:21 UTC, catbro666 commented
> 

done

2022-08-22 01:43 UTC, ms2008 approved these changes

2022-08-31 06:35 UTC, merged