chore(release): bump Kong's version number to 3.0.1
Kong/kong pull request #9428
Opened 2022-09-13 09:27 UTC by hanshuebner

2022-09-13 11:51 UTC, aboudreault approved these changes

2022-09-13 13:38 UTC, gszr approved these changes
Thinking out loud: should we also use the `suffix` field in master so that it doesn't get confusing to users? Right now it reads as if 3.0.1 was already released.

2022-09-13 14:49 UTC, kikito requested changes

2022-09-13 14:49 UTC, kikito commented on kong-3.0.1-0.rockspec
> +version = "3.0.1-0"
I think we should be bumping to "the next version that can be released from the current master".

`release/3.0.x` is a long-lived branch. All the members of the `3.0.x` family (including `3.0.1`) will be commits on that branch.

The next release that will come out from `master` is `3.1.0`, so I think that is the correct version to "preemptively bump to".
```suggestion
version = "3.1.0-0"
```

(rockspec filename would need to be updated as well)

2022-09-13 14:49 UTC, kikito commented on kong-3.0.1-0.rockspec
> +  tag = "3.0.1"
```suggestion
  tag = "3.1.0"
```

2022-09-13 14:49 UTC, kikito commented on kong/meta.lua
> +  patch = 1,
This also would need to be changed to 3.1.0

2022-09-14 10:28 UTC, kikito approved these changes

2022-09-14 18:45 UTC, merged