feat(report): route statics
Kong/kong pull request #9459
Opened 2022-09-22 06:13 UTC by StarlightIbuki

Fix FT-3217

2022-09-23 03:26 UTC, chronolaw commented on kong/conf_loader/init.lua
> +  route_minial_sync_interval = { typ = "number" },
should be `minimal`?

2022-09-23 03:26 UTC, chronolaw commented on kong/reports.lua
> +  reset_counter(ROUTE_HIT_TYPE_COUNT_KEY,_ping_infos.regex_path_matched)
style, add a blank after `,`

2022-09-23 03:26 UTC, chronolaw commented on spec/02-integration/04-admin_api/11-reports_spec.lua
> +        route_minial_sync_interval = 1,
`minimal`

2022-09-23 03:26 UTC, chronolaw commented on kong/router/init.lua
> +local default_minimal_interval = 60 -- 1 minute
constant should be upper case.

2022-09-23 03:26 UTC, chronolaw commented on kong/router/init.lua
> +    if premature then return end
bad style, should not in one line.

2022-09-23 07:12 UTC, chronolaw commented on kong/router/init.lua
> +local phonehome_statics
typo, should be `phonehome_statistics`

2022-09-23 07:12 UTC, chronolaw commented on kong/router/init.lua
> +local nkeys = require("table.nkeys")
I think that `nkeys` and `empty_table` should in `phonehome_sync_start do ... end` block

2022-09-23 07:12 UTC, chronolaw commented on kong/router/init.lua
> +          goto break1
should be a simple `break`?

2022-09-23 07:12 UTC, chronolaw commented on kong/router/init.lua
> +        goto break2
This `goto` is not a wise usage.

2022-09-23 07:40 UTC, StarlightIbuki commented
remember to fix typo in commit message when merging...

2022-09-23 07:45 UTC, StarlightIbuki commented on spec/01-unit/16-runloop_handler_spec.lua
> +    it("releases the lock when rebuilding the router fails #tt", function()
```suggestion
    it("releases the lock when rebuilding the router fails", function()
```

2022-09-23 08:15 UTC, dndx requested changes

2022-09-23 08:15 UTC, dndx commented on kong/router/init.lua
> +      reports.send("routes", route_report)
This is over complicating things, please remove all timers and semaphore from this.

We trigger a phone home for each router rebuild, please avoid making this more complicated than necessary for such a non-important feature that goes into patch releases.

We should simple follow how https://github.com/Kong/kong/blob/master/kong/api/routes/config.lua#L23 is done by sending a message when router is rebuild, and avoid bring in more complexity than necessary.

2022-09-23 08:15 UTC, dndx commented on kong/router/init.lua
> +      route_report.headers_count = route_report.headers_count + nkeys(headers)
These variables should be local variables until the end where the `route_report` can be created/assigned. Please avoid table access in a loop.

2022-09-23 08:15 UTC, dndx commented on kong/runloop/handler.lua
> +        Router.phonehome_sync_start(kong.configuration.route_minimal_sync_interval)
Again, please remove this needless background timer for phone home.

2022-09-23 08:18 UTC, dndx commented
Also, we should only create cherry pick PRs after the main PR into `master` is merged. Otherwise a lot of wasted work will happen when reviews are addressed.

2022-09-27 08:05 UTC, StarlightIbuki commented
Closing for rewriting the implementation.

2022-09-27 08:05 UTC, closed without merging