fix: add missing protocols field to plugins
Kong/kong pull request #9525
Opened 2022-10-11 07:09 UTC by GGabriele

### Summary

All plugin entities are expected to have a `protocols` schema field, but some plugin schemas are missing it. From a functional point of view, this doesn't have any impact, since the `protocols` field is still injected in the overall schema. But when plugin schemas are retrieved via the Admin API using the `/schemas/plugins/<name>` endpoint, then the "original" schema is returned. For example:

```
$ http :8001/schemas/plugins/prometheus
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 354
Content-Type: application/json; charset=utf-8
Date: Tue, 11 Oct 2022 06:42:47 GMT
Server: kong/3.0.0
X-Kong-Admin-Latency: 6

{
    "fields": [
        {
            "config": {
                "fields": [
                    {
                        "per_consumer": {
                            "default": false,
                            "type": "boolean"
                        }
                    },
                    {
                        "status_code_metrics": {
                            "default": false,
                            "type": "boolean"
                        }
                    },
                    {
                        "latency_metrics": {
                            "default": false,
                            "type": "boolean"
                        }
                    },
                    {
                        "bandwidth_metrics": {
                            "default": false,
                            "type": "boolean"
                        }
                    },
                    {
                        "upstream_health_metrics": {
                            "default": false,
                            "type": "boolean"
                        }
                    }
                ],
                "required": true,
                "type": "record"
            }
        }
    ]
}
```

This is problematic for decK, which uses this endpoint to inject schema defaults before doing a deployment, which can cause unnecessary/misleading diffs:

```
$ cat kong.yaml
_format_version: "3.0"
plugins:
  - name: prometheus

$ deck sync
updating plugin prometheus (global)  {
   "config": {
     "bandwidth_metrics": false,
     "latency_metrics": false,
     "per_consumer": false,
     "status_code_metrics": false,
     "upstream_health_metrics": false
   },
   "enabled": true,
   "id": "93aece4b-b813-4d9b-af28-f4c1c874f128",
   "name": "prometheus",
-  "protocols": [
-    "grpc",
-    "grpcs",
-    "http",
-    "https"
-  ]
 }

Summary:
  Created: 0
  Updated: 1
  Deleted: 0
```

### Full changelog

* add missing `protocols` field to plugin schemas

2022-10-11 07:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=9525) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=9525) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=9525) it.</sub>

2022-10-11 17:28 UTC, hbagdi commented
@bungle @gszr Is there a way to add an assertion in our test suite to ensure that something like this doesn't happen again (at least for bundled plugins)?

2022-10-25 22:45 UTC, hbagdi commented
@flrgh With your new powers, can you help us review this PR?
@GGabriele Please work with @flrgh to get this over the finish line.

2022-10-28 18:38 UTC, flrgh requested changes
@GGabriele code changes LGTM, thanks :+1: can you please add a CHANGELOG entry for this? We'll be good to merge once that's done.

2022-10-31 21:32 UTC, flrgh approved these changes

2022-10-31 23:00 UTC, merged