Add contributo images
Kong/kong pull request #9560
Opened 2022-10-15 18:20 UTC by harsh007-github

Added contributor's images to show respect to our beloved contributors

### Summary

### Full changelog

* [Implement ...]
* [Add related tests]
* ...

### Issue reference

Fix #_[issue number]_

2022-10-15 18:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kong?pullRequest=9560) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kong?pullRequest=9560) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kong?pullRequest=9560) it.</sub>

2022-10-19 09:00 UTC, chronolaw commented
Thanks for your contribution.

I think it is not a very useful change,  you could give us code to improve kong.

2022-10-19 09:09 UTC, hanshuebner approved these changes

2022-10-20 08:39 UTC, bungle approved these changes

2022-10-20 09:10 UTC, fffonion requested changes
@harsh007-github Thanks for your contribution. However, github already have contributors badges and I believe it's clear enough. And we don't have any third party badge walls in readme. Thus I'm rejecting this PR.

2022-10-20 09:17 UTC, fffonion commented
Also as there's technically nothing to be requeted for "Changes", I'm closing this PR. We acknowledge your contribution and appreciate your work took on completing and submitting this PR; but at this time, we will not move forward on merging this. We will still welcome your further contribution that are included in the [CONTRIBUTING](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#improving-the-documentation) scope.

2022-10-20 09:17 UTC, closed without merging