feat(db) support secrets referencing for string value of the map type
Kong/kong pull request #9706
Opened 2022-11-07 08:31 UTC by vm-001

### Summary

### Full changelog

* [Implement ...]
* [Add related tests]
* ...

### Issue reference

Fix #_[issue number]_

2022-11-08 08:19 UTC, vm-001 commented
I don't see Kong has test cases for dereferencing vault value for the plugin schema. So I added spec/02-integration/13-vaults/04-vault-plugin_spec.lua

2022-11-08 09:01 UTC, bungle requested changes

2022-11-08 09:06 UTC, vm-001 commented on kong/db/schema/init.lua
> +          local vaules = field.values
Ops... typo again. (I just feel adding a lint tool into the github workflow will reduce some review of typos back and forth.)

2022-11-22 16:07 UTC, closed without merging

2022-11-23 02:22 UTC, vm-001 commented
> We've added support to reference map type.
> 
> * [bc21540](https://github.com/Kong/kong/commit/bc215401d4eda52e000bdd27c9ece80211f71f55)
> * [3676324](https://github.com/Kong/kong/commit/3676324d1846cec72589f18ac153a29736dea18d)

Good!