chore(github) modify pull request template
Kong/kong pull request #9711
Opened 2022-11-07 19:24 UTC by kikito

### Summary

Modify the pull request template with a checklist so that we don't forget
commonly needed items:

* tests
* changelog
* docs
* ee cherry-pick

2022-11-16 17:34 UTC, RobSerafini requested changes

2022-11-17 02:53 UTC, dndx approved these changes

2022-11-17 02:54 UTC, dndx commented
@hbagdi is this ready to merge? If so, please remove the `do not merge` label.

2022-11-17 19:27 UTC, hbagdi approved these changes

2022-11-18 01:02 UTC, merged