docs(autodoc): correct example response data
Kong/kong pull request #9786
Opened 2022-11-20 17:38 UTC by mayocream

### Summary

Correct JSON response data of autodoc example.

### Checklist

- [ ] The Pull Request has tests
- [ ] There's an entry in the CHANGELOG
- [x] There is a user-facing docs PR against https://github.com/Kong/docs.konghq.com - PUT DOCS PR HERE

2022-11-24 08:23 UTC, ADD-SP requested changes

2022-11-24 08:23 UTC, ADD-SP commented on autodoc/admin-api/data/admin-api.lua
> +                        "default": true,
```suggestions
"default": false,
```

https://github.com/Kong/kong/blob/d52007a4457af151aed13585f171cb0eea5835f2/kong/plugins/key-auth/schema.lua#L18

2022-12-02 03:48 UTC, mayocream commented on autodoc/admin-api/data/admin-api.lua
> +                        "default": true,
nice catch!

2022-12-06 01:42 UTC, ADD-SP approved these changes

2022-12-26 05:20 UTC, dndx approved these changes

2022-12-26 05:21 UTC, merged