feat(cmd): stand-alone script to check kong health
Kong/kong pull request #9808
Opened 2022-11-22 21:21 UTC by locao

### Summary

This resty script checks if the Nginx master process needed by Kong is running. It provides the same functionality as `kong health`, but does not start a second Nginx for that. 

### Full changelog

* New resty script.
* Adapted current `kong health` tests.
* To do: obsolete `kong health`.

FTI-4452

2023-01-10 17:43 UTC, kikito approved these changes

2023-01-17 15:12 UTC, kikito requested changes

2023-01-17 15:12 UTC, kikito commented on bin/kong-health
> +  local x = kill.is_running(pid_file)
It seems `x` isn't used for anything. Should we remove this line?
```suggestion
```

2023-01-17 15:12 UTC, kikito commented on bin/kong-health
> +  local pid_file = pl_path.join(prefix, unpack({"pids", "nginx.pid"}))
I believe this is equivalent:
```suggestion
  local pid_file = pl_path.join(prefix, "pids", "nginx.pid")
```

2023-01-18 09:45 UTC, kikito approved these changes

2023-01-18 21:02 UTC, curiositycasualty approved these changes

2023-01-18 21:14 UTC, merged

2023-01-19 08:08 UTC, fffonion commented
we may need to add a line here https://github.com/Kong/kong/blob/master/build/package/nfpm.yaml#L30 to be able to package this in artifacts

2023-01-19 14:36 UTC, locao commented
> we may need to add a line here https://github.com/Kong/kong/blob/master/build/package/nfpm.yaml#L30 to be able to package this in artifacts

I see you already did it. Thank you!